### ISSUE TITLE
Projects with analyzers, those analyzers become dependencies in other projects

### ISSUE THREAD

**Issue by stuartstein777** [DotNetAnalyzers/StyleCopAnalyzers#2717] opened 2018-06-08 11:33 UTC
I have a  project that I have added some of these analyzers to, then I make that a nuget package.

When i add my nuget package to other projects, the analyzers become a dependency on that project and it installs their nuget package.

Is it possible to add these analyzers so I can have code analysis and rulesets, but not have them become dependencies?

e.g.:

![image](https://user-images.githubusercontent.com/22107263/41155992-fdf6724a-6b17-11e8-8e1f-a0c6b26e50c8.png)

When I make MessageTypes into a nuget and then add that nuget to another project, that project now has to install the StyleCop nuget packages. This makes no sense to me why that should be the case.

I'm probably being thick and doing something obviously wrong...

**Comment by sharwell** [comment] 2018-06-08 12:19
Duplicate of #2515 😄

**Closed by sharwell** 2018-06-08 12:19 UTC

**Comment by stuartstein777** [comment] 2018-06-08 12:21
Sorry! Didn't realise it was a duplicate.. Thank you!
