### ISSUE TITLE
False positive SA1101 on generic local methods

### ISSUE THREAD

**Issue by Lyrcaxis** [DotNetAnalyzers/StyleCopAnalyzers#3383] opened 2021-09-14 10:02 UTC
Generic local methods aren't recognized as local, and trigger SA1101.
StyleCop requires prefixing them with 'this.' even though compiler wouldn't run if it was prefixed.
![image](https://user-images.githubusercontent.com/32474602/133237410-37741a8b-b194-4e38-90d5-70cb0ac5c5c6.png)

Since we're at it, maybe it's supposed to be saying `'prefix **member** calls with this'`?

**Comment by sharwell** [comment] 2021-09-20 15:58
Duplicate of DotNetAnalyzers/StyleCopAnalyzers#3012

**Closed by sharwell** 2021-09-20 15:58 UTC
