### ISSUE TITLE
SA1650 Documentation mentions StyleCop.Settings

### ISSUE THREAD

**Issue by mario123456789o** [DotNetAnalyzers/StyleCopAnalyzers#2764] opened 2018-08-28 09:27 UTC
Hi,
The documentation to [SA1650](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1650.md) mentions to put the customDictionary.xml next to the StyleCop.Settings. But in the new StyleCop, there is no StyleCop.Settings in my understanding?
Where do I have to put my CustomDictionary.xml?

Regards
Mario

**Comment by sharwell** [comment] 2018-08-28 12:12
Duplicate of #1057

**Closed** 2018-08-28 12:11 UTC

**Comment by mario123456789o** [comment] 2018-08-31 10:38
OK thank you
I probably misunderstood the .md file.
