### ISSUE TITLE
Code triggers both SA1003 and SA1020

### ISSUE THREAD

**Issue by GregReddick** [DotNetAnalyzers/StyleCopAnalyzers#1775] opened 2015-11-16 17:43 UTC
See #1766 

Issue D4: Related to SA1003 and SA1020

The following code would only trigger SA1020 in classic StyleCop. The current analyzer triggers both SA1020 and SA1003.

```
int value = 1;
value ++;
```

**Comment by sharwell** [comment] 2015-11-16 18:13
This was likely fixed in #1749, but needs tests.

**Comment by sharwell** [comment] 2015-11-22 02:28
Looks like tests are already included. Marking as a duplicate of #1748.

**Closed by sharwell** 2015-11-22 02:28 UTC
Labels: bug, up for grabs
