### ISSUE TITLE
Should SA1118 (ParameterMustNotSpanMultipleLines) be reported for XDocument

### ISSUE THREAD

**Issue by RehanSaeed** [DotNetAnalyzers/StyleCopAnalyzers#2202] opened 2016-09-15 16:45 UTC
I often use `XDocument` in such a way that it looks like XML:

```
new XDocument(
    new XElement("Root",
        new XElement("Child")));
```

In my opinion, the above is a common approach to using `XDocument` to build up an XML document dynamically. It would be far more difficult to understand the XML document structure if the parameters were split up onto multiple lines.

**Comment by kveretennicov** [comment] 2016-09-15 17:12
+1 to @RehanSaeed's use case. We also use XDocument in this way, where indentation makes it easier to see XML element nesting.

**Comment by sharwell** [comment] 2016-09-15 20:10
It should not. This is a duplicate of :bug: #2200. :smile:

**Closed by sharwell** 2016-09-15 20:11 UTC
