### ISSUE TITLE
SA1629 should allow exclamation and question marks

### ISSUE THREAD

**Issue by Bouke** [DotNetAnalyzers/StyleCopAnalyzers#2850] opened 2019-01-06 17:10 UTC
The following triggers SA1629 on the remarks section and a fixit changes the sentence into "(...)queries!.". I think SA1629 should allow exclamation and question marks to properly end a sentence in addition to the period.

```
        /// <summary>
        /// The full datetime representation, including offset.
        /// </summary>
        /// <remarks>
        /// Unmapped! Not to be used in queries!
        /// </remarks>
```

**Comment by vweijsters** [comment] 2019-01-06 22:00
Duplicate of #2724

**Closed by vweijsters** 2019-01-06 22:00 UTC
Labels: duplicate
