### ISSUE TITLE
SA1208 Codefix puts the usings into the namespace

### ISSUE THREAD

**Issue by reaction1989** [DotNetAnalyzers/StyleCopAnalyzers#2251] opened 2016-12-14 09:17 UTC
I think this Codefix does more than it should. 

When applying this fix all the usings are put into the namespace. This should be handled by SA1200

**Comment by vweijsters** [comment] 2016-12-14 15:23
Due to the complexity of properly reordering using statements, there is no specific fix for SA1208. There is a fix that will properly order using statements according to the settings provided. This fix covers SA1200, SA1208, SA1209, SA1210, SA1211, SA1216, and SA1217. 

The behavior that you are seeing is therefore by design.

**Comment by bjornhellander** [comment] 2016-12-14 19:17
So what you can do, @reaction1989, is to configure StyleCop.Analyzers to behave as you like, according to https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/Configuration.md
Specifically where you want the usings: inside, outside or don't care.

**Comment by sharwell** [comment] 2016-12-24 06:02
@vweijsters I thought this was fixed as part of #2027?

**Comment by vweijsters** [comment] 2016-12-27 11:20
My bad, I forgot all about that. It has been fixed indeed, 1.1.0-beta1 contains the fix.
Just verified again to make sure that it is working as it should.

**Closed by vweijsters** 2016-12-27 11:20 UTC
Labels: question, resolved
