### ISSUE TITLE
SA1636: misfires on generated code for ProjName.NETCore.AssemblyInfo.cs

### ISSUE THREAD

**Issue by AArnott** [DotNetAnalyzers/StyleCopAnalyzers#2437] opened 2017-06-19 14:23 UTC
In StyleCop.Analyzers 1.0.2, .NET Core projects (from VS2017 15.3 Preview) produce the following warning:

> C:\git\PCLCrypto\obj\PCLCrypto.Tests.NETCore\Debug\netcoreapp1.0\PCLCrypto.Tests.NETCore.AssemblyInfo.cs(1,1): warning SA1636: The file header copyright text must match the copyright text from the settings. [C:\git\PCLCrypto\src\PCLCrypto.Tests.NETCore\PCLCrypto.Tests.NETCore.csproj]

The file in question has this content:

```
// Generated by the MSBuild WriteCodeFragment class.

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("PCLCrypto.Tests.NETCore")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyDescriptionAttribute("Package Description")]
[assembly: System.Reflection.AssemblyProductAttribute("PCLCrypto.Tests.NETCore")]
[assembly: System.Reflection.AssemblyTitleAttribute("PCLCrypto.Tests.NETCore")]
```

Notice the header is a "generated" header but not one that likely fits the mold that the analyzers know to skip.

**Comment by sharwell** [comment] 2017-06-19 15:02
This is caused by Microsoft/msbuild#1925; the behavior of StyleCop Analyzers with respect to the file's current content is by design.

Closing as a duplicate of #2314.

**Closed by sharwell** 2017-06-19 15:02 UTC
