### ISSUE TITLE
Require nameof()?

### ISSUE THREAD

**Issue by GregReddick** [DotNetAnalyzers/StyleCopAnalyzers#2358] opened 2017-05-23 00:35 UTC
I have the following older code:

```
if (arg == null)
{
    throw new ArgumentNullException("arg");
}
```

It would be nice to have some rule that would complain about arg and instead require:

```
if (arg == null)
{
    throw new ArgumentNullException(nameof(arg));
}
```
Using nameof() would be required on ArgumentException and things that inherit from it, such as ArgumentNullException, on any parameter where the parameter is named paramName.

This is a C# 6 feature, of course, so warnings and code fixes would only be applicable on projects using 6 or later. Thoughts?

**Comment by bjornhellander** [comment] 2017-05-23 06:35
Duplicate of #865.

**Closed** 2017-06-09 18:07 UTC
Labels: duplicate
