### ISSUE TITLE
SA1010	Opening square brackets should not be preceded by a space

### ISSUE THREAD

**Issue by daleao** [DotNetAnalyzers/StyleCopAnalyzers#3824] opened 2024-04-12 03:51 UTC
This rule doesn't make sense with collection initialization.
E.g. `int[] array = [1, 2, 3, 4];`

According to this rule, we should instead use
`int[] array =[1, 2, 3, 4];` or
`int[] array = { 1, 2, 3, 4 };`

**Comment by bjornhellander** [comment] 2024-04-12 05:04
This should go away if you switch to the latest beta.

**Comment by bjornhellander** [comment] 2024-04-12 05:05
Duplicate of #3687

**Comment by daleao** [comment] 2024-04-12 16:52
I am using Latest prerelease 1.2.0-beta.435.

**Comment by bjornhellander** [comment] 2024-04-12 18:42
1.2.0-beta.556 is the latest. It's fixed in that.

**Closed** 2024-04-15 15:49 UTC
