### ISSUE TITLE
False positive SA1009

### ISSUE THREAD

**Issue by auky-au** [DotNetAnalyzers/StyleCopAnalyzers#2681] opened 2018-05-09 18:27 UTC
I have the following code where StyleCop is giving a warning on it:
`public async Task<(bool, DateTime)> HasChanges(DateTime since)`

**Comment by sharwell** [comment] 2018-05-09 18:34
Duplicate of #2537

The 1.0 release only supports C# 6. You'll need to update to the latest 1.1 beta for C# 7 support.

**Closed by sharwell** 2018-05-09 18:34 UTC
