### ISSUE TITLE
SA1648 false positive when implementing static interface members

### ISSUE THREAD

**Issue by bruno-brant** [DotNetAnalyzers/StyleCopAnalyzers#3736] opened 2023-11-25 17:04 UTC
As the title says - SA1648 is triggered if we add a <inheritdoc /> in a static member that is implementing an interface:

```cs
interface IFoo
{
	/// <summary>Foobles the bars.</summary>
	public static abstract void Bar();
}

class Foo : IFoo
{
	// Line below triggers SA1648
	/// <inheritdoc/>
	public static void Bar() {}
}
```

**Comment by bjornhellander** [comment] 2023-11-26 09:47
Duplicate of #3595. Already fixed, but not yet released.

**Comment by sharwell** [comment] 2023-11-28 15:26
Duplicate of #3595

**Closed by sharwell** 2023-11-28 15:26 UTC
