### ISSUE TITLE
SA1122: Missfires in switch statement

### ISSUE THREAD

**Issue by Timo-Weike** [DotNetAnalyzers/StyleCopAnalyzers#3470] opened 2022-03-11 13:28 UTC
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/56654921e587211db0acc725ff33404dd623f720/documentation/SA1122.md?plain=1#L20

This rule is not correct in every context.
If we have code like
~~~ cs
string foo = ...;

var bar = foo switch
{
    "" => ..., // this "" will trigger the SA1122 rule 
}
~~~
But replacing it with string.Empty causes the error [CS0150](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0150)

**Comment by sharwell** [comment] 2022-03-11 16:42
Duplicate of #3028

**Closed by sharwell** 2022-03-11 16:42 UTC
Labels: duplicate
