### ISSUE TITLE
A button to fix everything!

### ISSUE THREAD

**Issue by TheTota** [DotNetAnalyzers/StyleCopAnalyzers#2580] opened 2017-12-13 23:03 UTC
When I use Stylecop Analyser on my projects, I just find myself going through each and every Stylecop-related warning and just chosing the fix option for that warning.
A button or something to fix every Stylecop-related warnings would be an interesting feature in my opinion, and a gain of time.

**Comment by vweijsters** [comment] 2017-12-14 20:34
I would agree on that, but unfortunately that behaviour is the responsibility of Visual Studio and it is not something that we can influence.

**Comment by sharwell** [comment] 2018-01-02 13:19
This is effectively a duplicate of dotnet/roslyn#8928.

**Closed by sharwell** 2018-01-02 13:19 UTC
Labels: external
