### ISSUE TITLE
NewtonSoft.JSon should not be added as "analyzer"

### ISSUE THREAD

**Issue by jessehouwing** [DotNetAnalyzers/StyleCopAnalyzers#1694] opened 2015-10-26 14:06 UTC
Recent upgrade has added NewtonSoft.JSon as an analyzer package, yet newtonsoft doesn't provide any analyzers.

```
 + <Analyzer Include="..\packages\StyleCop.Analyzers.1.0.0-beta013\analyzers\dotnet\cs\Newtonsoft.Json.dll" />
 + <Analyzer Include="..\packages\StyleCop.Analyzers.1.0.0-beta013\analyzers\dotnet\cs\StyleCop.Analyzers.dll" />
```

I suppose that this reference should not have been added at all and that the assembly should live in a tools folder of the nuget package instead.

**Comment by sharwell** [comment] 2015-10-26 14:22
This reference is required because our analyzers in StyleCop.Analyzers.dll use it during analysis. If the assembly is not listed as an analyzer, it will not be located during the build and any analyzer which attempts to use it will throw an exception. Marking as a duplicate of #1624.

**Comment by jessehouwing** [comment] 2015-10-26 14:55
It would be better if you were to use the same version of NewtonSoft JSon that ships with Visual Studio... Plus, it now forces all analyzers that depend on this assembly to use at least your version. Wouldn't statically registering an AppDomain.AssemblyResolve event allow you to fetch the assembly either from the same directory the main assembly is stored, or a tools assembly folder?!

**Comment by jessehouwing** [comment] 2015-10-26 14:58
This should do the trick: http://blogs.msdn.com/b/microsoft_press/archive/2010/02/03/jeffrey-richter-excerpt-2-from-clr-via-c-third-edition.aspx

**Comment by sharwell** [comment] 2015-10-26 15:03
> It would be better if you were to use the same version of NewtonSoft JSon that ships with Visual Studio...

I haven't noticed any negative interaction between our assembly reference and Visual Studio. What problem(s) would you anticipate solving by changing the version we use?

> Plus, it now forces all analyzers that depend on this assembly to use at least your version.

Everything involved uses strong names. What would keep another analyzer assembly from including its own version of Newtonsoft.Json (e.g. 6.x) and referencing that SxS?

> Wouldn't statically registering an AppDomain.AssemblyResolve event allow you to fetch the assembly either from the same directory the main assembly is stored, or a tools assembly folder?

It's possible, but I'd want a better understanding of the problems with the current approach as well as input from the analyzers team (e.g. @mavasani, @tmeschter) before going down this path.

**Comment by sharwell** [comment] 2015-10-26 15:05
I reopened the other issue for further discussion.

**Closed** 2015-10-26 15:04 UTC
Labels: duplicate
