### ISSUE TITLE
SA1649 for enums

### ISSUE THREAD

**Issue by KlemensE** [DotNetAnalyzers/StyleCopAnalyzers#2298] opened 2017-02-20 09:24 UTC
Having the following two files:

```
namespace TestNamespace
{
    public class MySuperClass
    {
    }
}
```

```
namespace TestNamespace
{
    public enum TestEnum
    {
        Test = 0
    }
}
```

SA1649 gets only reported for MySuperClass.

In my stylecop.json I have set `enum `as `topLevelTypes`.

Is it not possible to report this warning for enums?

**Comment by vweijsters** [comment] 2017-02-22 08:22
This is currently not supported unfortunately. I'm marking this as duplicate of #2223

**Closed by vweijsters** 2017-02-22 08:22 UTC
Labels: duplicate
