### ISSUE TITLE
Slow solution build times with SA1.1.0beta6

### ISSUE THREAD

**Issue by marko444** [DotNetAnalyzers/StyleCopAnalyzers#2639] opened 2018-03-14 10:19 UTC
Hello!

I notice that build time has slowed down considerably in this version compared to the SA1.0.2. 

In my case the time for 25 projects (a couple of standard 2.0, .net, debug, x64) went from ~24 seconds to ~45 seconds.

Is this a known fact and does anyone have any clue what could be the cause of the slowdown?

**Comment by sharwell** [comment] 2018-03-14 16:37
Can you try building using MSBuild from the command line `/p:ReportAnalyzer=true`, and let me know if it prints out the execution times for analyzers? I would be particularly interested in comparing the values from 1.0.2 and 1.1.0-beta006.

**Comment by marko444** [comment] 2018-03-14 20:49
I have attached a couple of reports.
[ReportAnalyzer.zip](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/files/1813017/ReportAnalyzer.zip)

**Comment by sharwell** [comment] 2018-03-15 04:37
@marko444 That page indicates that less than 3 seconds of the slowdown is caused by the analyzers. However, not everything is reported correctly by that tool. If you file a performance report using the other steps and link me to the feedback ticket it creates, I should be able to track down the cause. 😄

**Comment by marko444** [comment] 2018-03-15 08:35
I have recorded the build times here:
[Build 1.1.0-beta6](https://developercommunity.visualstudio.com/content/problem/215761/stylecop-analyzers-performance-impact-on-solution.html)
[Build 1.0.2](https://developercommunity.visualstudio.com/content/problem/215772/stylecop-analyzers-performance-impact-on-solution-1.html)

**Comment by sharwell** [comment] 2018-03-15 15:26
@marko444 Thanks, don't worry about how they get closed (probably as "other product").

**Comment by sharwell** [comment] 2018-03-25 18:57
This ended up being a duplicate of dotnet/roslyn#23637

**Closed by sharwell** 2018-03-25 18:57 UTC
