### ISSUE TITLE
Issue with SA1642 and private constructors

### ISSUE THREAD

**Issue by alareau** [DotNetAnalyzers/StyleCopAnalyzers#1147] opened 2015-08-07 19:36 UTC
In the old stylecop, SA1642 would suggest the following text for private constructors

SA1642 : CSharp.Documentation : The documentation text within the constructor's summary tag must begin with the text: Prevents a default instance of the <see cref="MyClass" /> class from being created.

With the analyzer, it now gives me the following (when you use the lightbulb icon)
/// Initializes a new instance of the <see cref="MyClass"/> class.

This was the suggestion for public constrictors
SA1642 : CSharp.Documentation : The documentation text within the constructor's summary tag must begin with the text: Initializes a new instance of the <see cref="MyClass" /> class.

Has the rule changed?

**Comment by sharwell** [comment] 2015-08-07 19:40
The change was by-design; see #413 for details.

This is a duplicate of #831.

We really need to implement #359 as a home for this information, but haven't yet. You can see this change is listed in a comment in that issue to make sure it gets included.

**Closed by sharwell** 2015-08-07 19:40 UTC
