### ISSUE TITLE
[Question] Are there details about next releases? When should we expect a new stable version?

### ISSUE THREAD

**Issue by julealgon** [DotNetAnalyzers/StyleCopAnalyzers#3275] opened 2020-12-16 15:08 UTC
The latest stable release is from April last year, and there have been several beta releases as recent as 8 days ago.

Do we have any ETA for when a new stable version will be available? I'd like to integrate this into a new solution but I'd like to avoid beta releases if at all possible, however the stable version is quite old at this point, without support for newer language features and such.

In particular, is there a specific reason why these beta releases are not stable?

**Comment by sharwell** [comment] 2020-12-16 16:13
Duplicate of #3241

**Closed by sharwell** 2020-12-16 16:13 UTC
