### ISSUE TITLE
False positive for SA1010

### ISSUE THREAD

**Issue by batzen** [DotNetAnalyzers/StyleCopAnalyzers#3598] opened 2023-01-21 07:33 UTC
The following code triggers SA1010 with "Opening square brackets should not be preceded by a space", even though it shouldn't trigger.

```
    public static bool IsExtended(ReadOnlySpan<char> path)
    {
        return path is ['\\', _, '?', '\\', ..] && (path[1] == '\\' || path[1] == '?');
    }
```

**Comment by bjornhellander** [comment] 2023-01-21 13:22
Duplicate of #3503

**Closed** 2023-02-03 17:16 UTC
