### ISSUE TITLE
SA1010 (no space before "[") conflicts with IDE0305 (use collection expression)

### ISSUE THREAD

**Issue by edwiles** [DotNetAnalyzers/StyleCopAnalyzers#3758] opened 2023-12-20 18:34 UTC
The use of C# 12's collection expressions, such as:

```csharp
List<int> list = [1, 2, 3];
```

causes SA1010 to fire:

```
Opening square brackets should not be preceded by a space.
```

Using version 1.2.0-beta.507.

**Comment by sharwell** [comment] 2023-12-20 18:38
Duplicate of #3687

**Closed by sharwell** 2023-12-20 18:38 UTC
