### ISSUE TITLE
SA1000 triggered for variable named var

### ISSUE THREAD

**Issue by appel1** [DotNetAnalyzers/StyleCopAnalyzers#2457] opened 2017-06-22 13:11 UTC
```csharp
foreach (var var in list)
{
   if (var.SomeProperty != null) // <- Triggers SA1000
   {
   }
}
```

I think SA1000 should only be triggered when var is used as a keyword.

**Comment by sharwell** [comment] 2017-06-22 13:56
Duplicate of #2419.

**Closed by sharwell** 2017-06-22 13:56 UTC
