### ISSUE TITLE
SA1309: FieldNamesMustNotBeginWithUnderscore  - add unit tests

### ISSUE THREAD

**Issue by macpak** [DotNetAnalyzers/StyleCopAnalyzers#435] opened 2015-01-31 21:16 UTC
Add tests for #85.

**Comment by macpak** [comment] 2015-01-31 21:17
Gonna do it together with #322.

**Comment by sharwell** [comment] 2015-01-31 21:44
Duplicate of #321

**Closed by sharwell** 2015-01-31 21:44 UTC
