### ISSUE TITLE
SA1010: Opening square brackets should not be preceded by a space conflicts with IDE0305

### ISSUE THREAD

**Issue by mggrand** [DotNetAnalyzers/StyleCopAnalyzers#3757] opened 2023-12-20 12:49 UTC
With C# 12, new [Collection Expressions](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/collection-expressions) are introduced. This simplification is provided with the Stylefix [IDE0305](https://learn.microsoft.com/de-de/dotnet/fundamentals/code-analysis/style-rules/ide0305). When this is applied, it conflicts with the SA1010 analyzer.

**Comment by sharwell** [comment] 2023-12-20 13:48
Duplicate of #3687

**Closed by sharwell** 2023-12-20 13:48 UTC
