### ISSUE TITLE
CA1062 fires on methods with 1 parameter marked as params

### ISSUE THREAD

**Issue by marcselis** [DotNetAnalyzers/StyleCopAnalyzers#3357] opened 2021-06-25 07:36 UTC
For example, the following code will result in a CA1062 in VS2022 Preview 1 (17.0.0), although that parameter can never be null.
```c#
public HeaderApiVersionReader( params string[] headerNames ) => HeaderNames.AddRange( headerNames );
```

Error message I receive is:

```txt
Severity  Code	      Description
Error     CA1062      In externally visible method 'HeaderApiVersionReader.HeaderApiVersionReader(params string[] headerNames)', validate parameter 'headerNames' is non-null before using it. If appropriate, throw an ArgumentNullException when the argument is null or add a Code Contract precondition asserting non-null argument.
```

**Comment by manfred-brands** [comment] 2021-06-25 10:18
Note that this error is not from StyleCop.
However, the warning is correct as someone could call this as `HeaderApiVersionReader(null)` or indirectly with an string array variable that is null.

**Comment by sharwell** [comment] 2021-06-25 17:01
Duplicate of https://github.com/dotnet/roslyn-analyzers/issues/4572

**Closed by sharwell** 2021-06-25 17:01 UTC
