### ISSUE TITLE
SA1312 incorrectly triggers for events.

### ISSUE THREAD

**Issue by jimmymain** [DotNetAnalyzers/StyleCopAnalyzers#1415] opened 2015-09-08 05:51 UTC
given the code below, the rule is suggesting that `OnAnEvent` be renamed to start with lower case.
Does [#SA1312](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1312.md) definitely apply to events, this doesn't seem correct?

```
    public interface IInterface
    {
        event EventHandler<EventArgs> OnAnEvent;
    }
```

**Comment by sharwell** [comment] 2015-09-08 11:34
Duplicate of #1340.

**Closed by sharwell** 2015-09-08 11:34 UTC
Labels: duplicate
