### ISSUE TITLE
SA 1002 - False warning.

### ISSUE THREAD

**Issue by dmitriyse** [DotNetAnalyzers/StyleCopAnalyzers#1807] opened 2015-11-22 16:35 UTC
for (;;) is not processed as valid but should (at least classic stylecop passes this code).
Also R#10 auto format always converts for(; ;) to for (;;).

**Comment by sharwell** [comment] 2015-11-22 17:10
This is a duplicate of #1489.

**Closed by sharwell** 2015-11-22 17:10 UTC
