### ISSUE TITLE
SA1119 shows incorrectly when using type matching

### ISSUE THREAD

**Issue by jimmymain** [DotNetAnalyzers/StyleCopAnalyzers#2598] opened 2018-01-18 08:54 UTC
SA1119 indicates extra parenthesis below, but the parenthesis are **not** redundant in this case.

```` c#
if (!(tag is ITagWireResponseMessage rsp))
    throw SomeException();

rsp.DoStuff();
rsp.DoMoreStuff();
````

**Comment by vweijsters** [comment] 2018-01-18 20:14
Duplicate of #2372

**Closed by vweijsters** 2018-01-18 20:14 UTC
Labels: duplicate
