### ISSUE TITLE
SA1313 Allow primary constructor parameters to start with underscore.

### ISSUE THREAD

**Issue by Psichorex** [DotNetAnalyzers/StyleCopAnalyzers#3790] opened 2024-01-29 17:13 UTC
It would be nice to have a perhabs configurable way to prevent primary constructors cause SA1313 warnings when their parameters start with underscore. 
This would actually support the naming convention of private fields to start with underscore.

**Comment by sharwell** [comment] 2024-02-05 13:36
Duplicate of #3752

**Closed by sharwell** 2024-02-05 13:36 UTC
