### ISSUE TITLE
StatementMustNotUseUnnecessaryParenthesis forces removing needed paranthesis

### ISSUE THREAD

**Issue by idigra** [DotNetAnalyzers/StyleCopAnalyzers#2828] opened 2018-11-22 10:00 UTC
The mentioned rules claims that the following line is illegal:
            if (maybe.HasNoValue || !(maybe.Value is TTo value))
(maybe is a struct of type Maybe<T> from CSharpFunctionalExtensions nuget).

However it is not syntactically equivalent to remove this parenthesis. Without them, the compiler complains that operator "!" cannot be applied on maybe.Value.

**Comment by sharwell** [comment] 2018-11-24 21:57
Duplicate of #2372

**Closed by sharwell** 2018-11-24 21:57 UTC
