### ISSUE TITLE
SA1000 conflict with csharp_space_between_method_call_name_and_opening_parenthesis in case of new implicit type

### ISSUE THREAD

**Issue by ltvan** [DotNetAnalyzers/StyleCopAnalyzers#3382] opened 2021-09-04 18:26 UTC
In the case of creating new implicit type, SA1000 requires space after `new`, which conflict with `csharp_space_between_method_call_name_and_opening_parenthesis`.

```csharp
// csharp_space_between_method_call_name_and_opening_parenthesis = false
SomeMethod(); // SA1008 conform
Person a = new() // SA1000 violated
{
    Name = "Jone"
};

// csharp_space_between_method_call_name_and_opening_parenthesis = true
SomeMethod (); // SA1008 violated
Person a = new () // SA1000 conform
{
    Name = "Jone"
};

```

Environment: VS2019

**Comment by sharwell** [comment] 2021-09-10 16:20
Duplicate of #3214

**Closed by sharwell** 2021-09-10 16:20 UTC
Labels: duplicate
