### ISSUE TITLE
SA1210 and SA1208 are ignored when using statements are inside a file-scoped namespace.

### ISSUE THREAD

**Issue by mayssamm** [DotNetAnalyzers/StyleCopAnalyzers#3764] opened 2023-12-28 09:25 UTC
I have SA1200 enabled, so, the using statements are inside the namespace. I am also using file-scoped namespaces. This makes stylecop ignore the order. If I switch back to using the namespace with brackets instead of the statement, the error messages appear.

Here is a simple example:

```
namespace MyNameSpace;

using B.C;
using A.B;
using System.X;

```
This produces no warnings but as soon as I switch to:
```
namespace MyNameSpace
{
using B.C;
using A.B;
using System.X;
}

```
both SA1208 and SA1210 show up in the warnings.

**Comment by sharwell** [comment] 2023-12-28 13:56
Duplicate of #3437

**Closed by sharwell** 2023-12-28 13:56 UTC
