### ISSUE TITLE
Possible conflict between SA1009 and IDE recommendation

### ISSUE THREAD

**Issue by nelsonprsousa** [DotNetAnalyzers/StyleCopAnalyzers#3228] opened 2020-11-04 19:26 UTC
The following code causes a [SA1009](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1009.md) violation:

```c#
public async Task Example()
{
	serviceMock
		.Setup(x => x.Get())
		.ReturnsAsync(default(MyClass)!);
}
```

I believe this should be an exception and we should use `default(MyClass)!` instead of `default(MyClass) !`

**Comment by sharwell** [comment] 2020-11-05 14:42
Can you check if this is a duplicate of #3143?

**Comment by nelsonprsousa** [comment] 2020-11-05 15:31
> Can you check if this is a duplicate of #3143?

Yeap, seems like it is. I tested with StyleCop.Analyzers.Unstable v1.2.0.261 and it is as expected 👍 

Is there an expected date for this fix to be released? Thank you 🙏

**Comment by sharwell** [comment] 2020-11-05 15:40
> Is there an expected date for this fix to be released?

My general recommendation is to just use the latest `-beta` package.

**Comment by sharwell** [comment] 2020-11-05 15:40
Duplicate of #3143

**Closed by sharwell** 2020-11-05 15:40 UTC
Labels: c# 8
