### ISSUE TITLE
We need to execute stylecop ruleset from command line.

### ISSUE THREAD

**Issue by suras48** [DotNetAnalyzers/StyleCopAnalyzers#2596] opened 2018-01-15 11:47 UTC
We have used StylecopCLI.exe to execute the rulesets but it does contain its own dll which we cant included in our porject.So is der any specific nuget package or any other tool available.

From Visual studio we were able to add the nuget to our project and by running from visual studio its is possible to perform code anaylsis even with customized ruleset.
While trying from a batch file it will first combile the code at that time it will refers the dll for rules instead of customized rules and all  warning related to all rules are displayed i console..

**Comment by sharwell** [comment] 2018-05-03 02:37
Duplicate of #2571

**Closed by sharwell** 2018-05-03 02:37 UTC
