### ISSUE TITLE
SA1009 ClosingParenthesisMustBeSpacedCorrectly - issue with list of tuples

### ISSUE THREAD

**Issue by DrGriff** [DotNetAnalyzers/StyleCopAnalyzers#2911] opened 2019-03-05 10:00 UTC
Get an error in the following circumstances:

`private static List<(string Path, string File)> MethodName (TypeName request)`

and

`var response = new List<(string Path, string File)>();`

It doesn't like the ")>" syntax

(using v1.0.2 of StyleCop.Analyzers)

**Comment by sharwell** [comment] 2019-03-05 13:41
Support for C# 7 (including tuples) was first added in the 1.1 releases. 😄

**Comment by sharwell** [comment] 2019-03-05 13:43
Duplicate of #2522

**Closed by sharwell** 2019-03-05 13:43 UTC
