### ISSUE TITLE
Stylecop.Analyzers throws  NullReferenceExceptions for SA1135 after upgrading to VS2019 16.5.

### ISSUE THREAD

**Issue by m-ringler** [DotNetAnalyzers/StyleCopAnalyzers#3138] opened 2020-03-24 15:39 UTC
We're using Stylecop.Analyzers in several projects targeting .NET framework 4.6.2. After upgrading Visual Studio 2019 from 16.4.6 to 16.5 we were getting lots of NullReferenceExceptions in the build (with Stylecop.Analyzers 1.1.118). We tried upgrading to Stylecop.Analyzers 1.2.0-beta.164, but we're still getting NullReferenceExceptions for SA1135.

**Comment by sharwell** [comment] 2020-03-24 16:30
The NullReferenceException should produce an AD0001 diagnostic with context and call information. Can you include that?

**Comment by m-ringler** [comment] 2020-03-25 06:56
With VS 2019 v16.5.1 and Stylecop.Analyzers 1.1.118, the AD0001 does not include more information: 
~~~
Severity	Code	Description	Project	Project Rank	Path	File	Line	Column	Category	Source	Suppression State	Tool
Error	AD0001	Analyzer 'StyleCop.Analyzers.ReadabilityRules.SA1135UsingDirectivesMustBeQualified' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.	My.Project	3	C:\Path.To\My.Project	C:\Path.to\My.Project\CSC	1	1	Build	Build	Active	Compiler
~~~

**Comment by sharwell** [comment] 2020-03-28 07:41
Duplicate of #3136

**Closed by sharwell** 2020-03-28 07:41 UTC
Labels: bug, up for grabs
