### ISSUE TITLE
What is the justification for trailing commas in SA1413??

### ISSUE THREAD

**Issue by DRAirey1** [DotNetAnalyzers/StyleCopAnalyzers#2260] opened 2016-12-27 21:18 UTC
I just downloaded the 1.1.0.0 beta001 and a boatload of errors kicked out of what had been a very clean solution.  What is the justification for this rule?  Trailing commas look like you missed a value.  It doesn't add to the readability and it's just an excuse to be lazy.  This is a big breaking change for me.

**Comment by sharwell** [comment] 2016-12-27 21:20
This is a duplicate of #2238. My recommendation is to disable the new rule via a rule set file if you don't want to have it applied (and it will continue to be disabled in the future).

**Closed by sharwell** 2016-12-27 21:20 UTC
Labels: duplicate
