### ISSUE TITLE
SA1313: Allow to use unlimited number of underscores in lambda expressions

### ISSUE THREAD

**Issue by ivanlomakov** [DotNetAnalyzers/StyleCopAnalyzers#2620] opened 2018-02-13 18:31 UTC
For now the following expression raises no error
```C#
Func<int, bool> Do = _ => true;
```

But if you need the following expression an error occurs as double underscore "__" is not allowed.
```C#
Func<int, int, bool> Action = (_, __) => true;
```
Could you please add support for unlimited number of underscores in lambda expressions?

**Comment by sharwell** [comment] 2018-02-13 18:45
Duplicate of #1606

**Closed by sharwell** 2018-02-13 18:45 UTC
