### ISSUE TITLE
Stylecop Analyzers throw an exception on record types

### ISSUE THREAD

**Issue by matteo-mosca** [DotNetAnalyzers/StyleCopAnalyzers#3366] opened 2021-07-08 11:44 UTC
When using .Net 5 / C# 9 record types, SyleCopAnalyzers throws an exception on rule 1649 and the only way to make it go away is to disable that rule altogether from the ruleset file, which is not very desirable. The exception thrown states as follows:

> AD0001	Analyzer 'StyleCop.Analyzers.DocumentationRules.SA1649FileNameMustMatchTypeName' threw an exception of type 'System.ArgumentException' with message 'Unhandled declaration kind: RecordDeclaration'.

The correct behavior should be Stylecop correctly recognizing record types as they are part of official C# 9 language specification.

**Comment by sharwell** [comment] 2021-07-08 15:59
Duplicate of #3213

**Closed by sharwell** 2021-07-08 15:59 UTC
