### ISSUE TITLE
SA1023 is reported for cast operations

### ISSUE THREAD

**Issue by Tinister** [DotNetAnalyzers/StyleCopAnalyzers#1487] opened 2015-09-17 03:13 UTC
Here's some code:

	fixed (byte* p = &bytes[index])
	{
		int i = *((int*)p);
	}

SA1023 is reported and wants to fix the cast operation to `*((int* )p)`

The suggested fix violates SA1003 and SA1009.

**Comment by sharwell** [comment] 2015-09-17 03:15
Duplicate of #1457.

**Closed by sharwell** 2015-09-17 03:15 UTC
