### ISSUE TITLE
UseLambdaSyntax analyzer throws null reference exception

### ISSUE THREAD

**Issue by macrian** [DotNetAnalyzers/StyleCopAnalyzers#2895] opened 2019-02-19 17:43 UTC
When this rule is enabled in my codebase a null reference exception in the analyzer is thrown. Whether I build through visual studio or using console version of MsBuild.
Unfortunately I cannot provide any code to reproduce this issue due the code being proprietary but if anyone more information is required, I am happy to oblige

**Comment by sharwell** [comment] 2019-02-19 17:48
When the code fix crashes, the gold bar in Visual Studio should provide a stack trace that will help us resolve this.

**Comment by sharwell** [comment] 2019-02-22 00:39
Duplicate of #2902

**Closed by sharwell** 2019-02-22 00:39 UTC
