### ISSUE TITLE
Allow configuration of SA0001:XmlCommentAnalysisDisabled

### ISSUE THREAD

**Issue by adamralph** [DotNetAnalyzers/StyleCopAnalyzers#2192] opened 2016-08-22 07:33 UTC
For some projects, I don't want to enable XML documentation and I don't want this warning either. I should be able to disable this rule in StyleCop.json.

**Comment by sharwell** [comment] 2016-08-22 12:20
This issue is a duplicate of #2191, with one big caveat. Roslyn will not behave the way you expect when you have XML documentation disabled, and a large number of rules will misbehave. I recommend reading over the [documentation for SA0001](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA0001.md), and using a ruleset file to disable the other rules which tend to be the original reason people turn off XML output (e.g. CS1573, CS1591).

**Closed by sharwell** 2016-08-22 12:20 UTC

**Comment by adamralph** [comment] 2016-08-22 21:53
Thanks. Does that mean that I *have* to enable XML output no matter what, unless I want all sorts of strange effects?

It's not really ideal. There's only a subset of projects I work on where switching on XML output makes sense, but I still want to use StyleCop in those projects for everything else.

**Comment by sharwell** [comment] 2016-08-23 12:50
@adamralph Everything seems to work better if XML output is always enabled. We would have otherwise needed to make a bunch of exceptions in the analyzers and provide separate behavior for the case where XML output is disabled. I'm not sure why, but the setting affects the internal parsing behavior of the compiler in addition to the output.

Also note that when XML output is disabled you'll face other bugs too, like dotnet/roslyn#2773.

**Comment by adamralph** [comment] 2016-08-23 13:50
@sharwell OK, so it seems the problem is more deep rooted than this analyzer package, and is in Roslyn itself. Fair enough, I guess enabling docs when I don't need them isn't too costly. Shame that this paper cut has to exist though.
