### ISSUE TITLE
SA1119 (Statements must not use unnecessary parenthesis) suggest wrong fix

### ISSUE THREAD

**Issue by Nicte** [DotNetAnalyzers/StyleCopAnalyzers#2776] opened 2018-09-07 14:10 UTC
Version: 1.0.2

I have the following line:

```C#
if (!(actionExecutedContext.Request.GetDependencyScope().GetService(typeof(FileDispatchContext)) is FileDispatchContext dbContext))
```

The parenthesis are necessary here because the proposed fix results in:

```C#
if (!actionExecutedContext.Request.GetDependencyScope().GetService(typeof(FileDispatchContext)) is FileDispatchContext dbContext)
```

Which fails because "Error: CS0023 Operator '!' cannot be applied to operand of type 'object'"

**Comment by sharwell** [comment] 2018-09-07 14:31
Duplicate of #2372

**Closed by sharwell** 2018-09-07 14:31 UTC
