### ISSUE TITLE
SA1127 code fix indents too far when XML comments are present

### ISSUE THREAD

**Issue by nbarbettini** [DotNetAnalyzers/StyleCopAnalyzers#1958] opened 2015-12-13 02:07 UTC
I noticed this :bug: yesterday. I don't think it's RC2-related; I probably just never hit this scenario before.

This code reports SA1127 (Generic type constraints must be on their own line):
```csharp
/// <summary>
/// Test class
/// </summary>
/// <typeparam name="T">The type.</typeparam>
public class Foo<T> where T : IDisposable
{
}
```

The expected fix is:
```csharp
public class Foo<T>
    where T : IDisposable
{
}
```

The code fix instead produces:
```csharp
public class Foo<T>
        where T : IDisposable
    {
}
```

This **only** happens when XML comments are present on the element. It indents as expected when XML comments are missing.

**Comment by nbarbettini** [comment] 2015-12-13 02:08
Since I wrote the code fix for SA1127, I'll fix this. :+1:

**Comment by sharwell** [comment] 2015-12-13 06:36
Duplicate of #1652.

**Closed by sharwell** 2015-12-13 06:36 UTC
