### ISSUE TITLE
SA1009 incorrect behaviour on getneric with tuple type

### ISSUE THREAD

**Issue by AdamWyzgol** [DotNetAnalyzers/StyleCopAnalyzers#2702] opened 2018-05-23 08:51 UTC
I have issue with SA1009 rule when I use generic with tuple, for example:
`Task<(string val1,int val2)>` show warning that after  `)` I should put space that is incorrect in this case.

**Comment by vweijsters** [comment] 2018-05-23 08:54
Duplicate of #2537

**Closed by vweijsters** 2018-05-23 08:54 UTC
Labels: duplicate
