### ISSUE TITLE
SA1000 - The spacing around a C# keyword is incorrect.

### ISSUE THREAD

**Issue by DRAirey1** [DotNetAnalyzers/StyleCopAnalyzers#3459] opened 2022-02-17 16:04 UTC
I really don't give a crap whether the right syntax is "new()" or "new ()". Can we make the rule consistent with the Visual Studio Text formatter so that when I hit &lt;ctrl&gt;K&lt;ctrl&gt;D I don't get dozens of these errors popping up?

**Comment by sharwell** [comment] 2022-02-17 16:21
Duplicate of #3214

**Closed by sharwell** 2022-02-17 16:21 UTC
Labels: duplicate

**Comment by pelaez87** [comment] 2022-02-23 19:49
I have same issue and already tried with latest beta nuget package
When I auto format code with Visual Studio 2022 and code is as in your unit test **int a = new();** stylecop hints the SA1000, so if I put the space and autoformat again (which removes the space) it's an endloop game.

**Comment by sharwell** [comment] 2022-02-23 21:55
@pelaez87 StyleCop Analyzers 1.2.0-beta.261 and newer will not report SA1000 on `new()`. If you are seeing SA1000, then either you have an older version or possibly are using a different StyleCop product than this. 😄

**Comment by DRAirey1** [comment] 2022-02-23 22:37
> @pelaez87 StyleCop Analyzers 1.2.0-beta.261 and newer will not report SA1000 on `new()`. If you are seeing SA1000, then either you have an older version or possibly are using a different StyleCop product than this. 😄

... or have a serious aversion to taking anything labelled 'beta' because of highly negative past experience.

**Comment by pelaez87** [comment] 2022-02-24 06:36
> @pelaez87 StyleCop Analyzers 1.2.0-beta.261 and newer will not report SA1000 on `new()`. If you are seeing SA1000, then either you have an older version or possibly are using a different StyleCop product than this. 😄

You are right, for some reason when I told Nuget manager to install it, it failed silently. Working fine with latest beta
