### ISSUE TITLE
SA1000/SA1008 In conflict with Visual Studio regarding spacing of C#9 Target-typed new expressions 

### ISSUE THREAD

**Issue by rsnell-usgs** [DotNetAnalyzers/StyleCopAnalyzers#3326] opened 2021-03-30 23:28 UTC
StyleCop demands that a space is used between the new keyword and the opening parenthesis when using C#9's new [target-typed new expression](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-9) feature:

`private List<WeatherObservation> _observations = new();`

If a space is added to satisfy StyleCop Visual Studio 2019 will remove it during code-cleanup when using default spacing settings in Code Style Options ("Insert space between method name and opening parenthesis", off by default). If this VS setting is changed to "on" to ensure the added space is kept then all other method calls are formatted accordingly and StyleCop subsequently issues SA1008 warnings for all method calls.

**Comment by sharwell** [comment] 2021-03-30 23:35
Duplicate of #3214

**Closed by sharwell** 2021-03-30 23:35 UTC
Labels: duplicate
