### ISSUE TITLE
Invalid Cert Warning For Documentation

### ISSUE THREAD

**Issue by anorborg** [DotNetAnalyzers/StyleCopAnalyzers#2646] opened 2018-03-19 16:53 UTC
When attempting to go to the docs referenced in the readme: https://stylecop.pdelvo.com/

I receive an invalid cert warning:

<img width="1037" alt="capture 2018-03-19 at 9 52 07 am" src="https://user-images.githubusercontent.com/264755/37609817-54c6aede-2b5b-11e8-968a-b10d3ad733b5.png">

**Comment by sharwell** [comment] 2018-03-20 06:22
Duplicate of #2569

**Closed by sharwell** 2018-03-20 06:22 UTC
