### ISSUE TITLE
code fixes for SA1600.

### ISSUE THREAD

**Issue by jimmymain** [DotNetAnalyzers/StyleCopAnalyzers#1759] opened 2015-11-12 05:30 UTC
Hi,

The old style cop code fixes in resharper used to provide default text for properties and methods that made it really easy to document code elements.

I note that SA1600 does not currently have a code fix.

I would be open to implementing it myself if I still needs to be done.

**Comment by sharwell** [comment] 2015-11-12 05:36
The one case where we currently support a code fix for SA1600 (and CS1591) is [`InheritdocCodeFixProvider`](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/StyleCop.Analyzers/StyleCop.Analyzers.CodeFixes/DocumentationRules/InheritdocCodeFixProvider.cs). In general we've avoided providing code fixes for documentation except in cases where we expect to provide *meaningful* documentation. Specific cases include:

* Adding `<inheritdoc/>` to undocumented elements which override or implement an inherited member (this is the previously mentioned code fix)
* The `<returns>` element for asynchronous unit tests
* The `<value>` element for properties that are already documented with `<summary>`
* The `<summary>` element for constructors and finalizers (as specified by SA1642/SA1643)

**Comment by sharwell** [comment] 2015-11-12 05:40
I'm marking this as a duplicate of #764.

**Closed by sharwell** 2015-11-12 05:40 UTC
