### ISSUE TITLE
SA1402 is not raised when declaring multiple types in a file-scoped namespace

### ISSUE THREAD

**Issue by Arthri** [DotNetAnalyzers/StyleCopAnalyzers#3851] opened 2024-05-29 15:19 UTC
```cs
namespace Z;

public class X {}

public class Y {}
```
doesn't trigger SA1402, but
```cs
public class X {}

public class Y {}
```
and
```cs
namespace Z
{
    public class X {}

    public class Y {}
}
```
do

**Comment by bjornhellander** [comment] 2024-05-29 19:13
Duplicate of #3435

**Closed** 2024-05-30 03:29 UTC
