### ISSUE TITLE
False positive for SA1008 when pattern matching

### ISSUE THREAD

**Issue by mheyman** [DotNetAnalyzers/StyleCopAnalyzers#3400] opened 2021-11-10 15:56 UTC
Code like
```csharp
if (shape is not (Polygon or MultiPolygon))
{
}
```
causes an SA1008 "Opening parenthesis should be spaced correctly" warning when it _probably_ shouldn't.

**Comment by sharwell** [comment] 2021-11-10 16:45
Duplicate of #3230

**Closed by sharwell** 2021-11-10 16:45 UTC
