### ISSUE TITLE
SA1008 conflicts with VS autoformatting for delegates

### ISSUE THREAD

**Issue by yaakov-h** [DotNetAnalyzers/StyleCopAnalyzers#1669] opened 2015-10-22 04:07 UTC
```
namespace SampleApp
{
    using System;

    public class Class1
    {
        public static void Main(string[] args)
        {
            Foo(delegate(string bar)
            {
                Console.WriteLine("{0}", bar);
            });

            Console.ReadKey();
        }

        public static void Foo(Action<string> action)
        {
            action("bar");
        }
    }
}
```

The above code satisfies SA1008, however if I use Visual Studio 2015's automatic formatting (Ctrl+K, Ctrl+D), it adds a space after `delegate` as so:

```
Foo(delegate (string bar)
{
	Console.WriteLine("{0}", bar);
});
```

Is this a StyleCop issue, or a Visual Studio issue?

**Comment by sharwell** [comment] 2015-10-22 04:24
The documentation for SA1008 is ambiguous. The documentation for SA1000 does not mention the `delegate` keyword at all. @vweijsters What does StyleCop Classic do?

**Comment by GregReddick** [comment] 2015-10-22 04:50
StyleCop classic does not want a space after the delegate.

There should be an option for this in the Visual Studio Options (Text Editor > C# > Formatting > Spacing), but I didn't find one that affects this.

**Comment by sharwell** [comment] 2015-10-22 05:39
For now I'm going to close this as **wontfix** since it matches the behavior of StyleCop Classic (which means it's by design).

**Closed by sharwell** 2015-10-22 05:39 UTC
Labels: needs discussion

**Comment by Przemyslaw-W** [comment] 2015-10-22 07:33
https://github.com/dotnet/roslyn/issues/3257

**Comment by yaakov-h** [comment] 2015-10-22 07:34
Thanks!

**Comment by AArnott** [comment] 2023-11-22 18:35
@sharwell, would you reconsider fixing this? I don't think anyone cares about Stylecop Classic any more. But if I can't keep Format Document from fighting StyleCop, I'll have to just turn the SA1008 rule off. Considering SA1008 does a lot of good, I'd hate to turn it off completely. But fighting with Format Document is a non-starter.

**Comment by sharwell** [comment] 2023-11-22 19:32
Note that a workaround exists, which may explain why reports here are infrequent. This formatting issue does not affect `delegate { ... }` syntax, and the `delegate(...) { ... }` syntax can be rewritten using the more recent syntax `(...) => { ... }` in all cases we are aware of.
