### ISSUE TITLE
Nullable array declaration, contradictory analyzer messages

### ISSUE THREAD

**Issue by krestenlaust** [DotNetAnalyzers/StyleCopAnalyzers#3680] opened 2023-07-25 13:54 UTC
![SA1011 code example](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/assets/17174333/b4de4092-392b-4877-9a2d-36b63f2c5c04)
SA1011: Closing square bracket should be followed by a space.

![SA1018](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/assets/17174333/cd925c20-998d-4e69-a4e9-414028017674)
SA1080: Nullable type symbol should be preceded by a space.

**Solution**
Disregard SA1011, when it's the nullable character.

**Source context**
Line: 142
[WindowClient.cs.txt](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/files/12161971/WindowClient.cs.txt)

**Info**
StyleCop.Analyzers == 1.1.118

**Comment by sharwell** [comment] 2023-07-25 13:55
Duplicate of #2927

**Comment by krestenlaust** [comment] 2023-07-25 13:56
Ah, sorry about that 😅

**Closed by sharwell** 2023-07-25 13:55 UTC
