### ISSUE TITLE
Incorrect SA1008 with pattern matching tuple

### ISSUE THREAD

**Issue by jizc** [DotNetAnalyzers/StyleCopAnalyzers#3556] opened 2022-09-07 15:56 UTC
This is a similar issue to #3476. The following code results in SA1008:
```csharp
if (obj is FrameworkElement { Tag: (bool item1, bool item2) })
//                                 ^ SA1008 Opening parenthesis should not be preceded by space
```
Using StyleCop.Analyzers 1.2.0-beta.435.

**Comment by ssg** [comment] 2022-11-10 20:11
This happens with other pattern matching structures too:
<img width="794" alt="image" src="https://user-images.githubusercontent.com/241217/201196045-16a03082-466a-48de-934d-f0718f82921c.png">

**Comment by bjornhellander** [comment] 2022-11-18 05:14
@ssg's case seems to be a duplicate of #3230. It does not reproduce for me with 1.2.0-beta.435.

**Comment by ssg** [comment] 2022-11-18 05:15
@bjornhellander You're probably right.

**Closed** 2023-02-09 19:02 UTC
Labels: bug, up for grabs, c# 9
