### ISSUE TITLE
Analyzers do not work on DNX package project

### ISSUE THREAD

**Issue by ivaylokenov** [DotNetAnalyzers/StyleCopAnalyzers#1966] opened 2015-12-16 19:59 UTC
I am creating a package project. Added analyzers but they do not run and Code Analysis shows nothing while I am sure not everything in the code is in perfect condition.

My project.json is:

```
"dependencies": {
    "Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
    "Microsoft.AspNet.Http": "1.0.0-rc1-final",
    "StyleCop.Analyzers": "1.0.0-rc2"
  },

  "frameworks": {
    "dnx451": { },
    "dnxcore50": { }
  }
```

**Comment by sharwell** [comment] 2015-12-16 20:20
Duplicate of #806.

**Closed by sharwell** 2015-12-16 20:20 UTC
