### ISSUE TITLE
Code fix with SA1201 seems to very unpredictable, possibly in conjunction with Ruleset

### ISSUE THREAD

**Issue by brphelps** [DotNetAnalyzers/StyleCopAnalyzers#3185] opened 2020-08-26 21:53 UTC
I'm seeing a strange issue in one of my projects (latest VS2019 on .net core 2.2.8, SDK 3.1) where the StyleCop Analyzers correctly identify SA1201 as being violated but _do not_ show the code fix for the issue in the context menu. Ex:

![image](https://user-images.githubusercontent.com/10023676/91360601-9ac13a80-e7ab-11ea-98f3-f1ce66dabb3e.png)

Clicking on "show potential fixes" takes me here: 
![image](https://user-images.githubusercontent.com/10023676/91360620-a57bcf80-e7ab-11ea-979f-74712d246196.png)

Interestingly, in this same project, I was able to see what I expected, but this was only _before_ I tried adding a code analysis ruleset (which I then reverted observing this new behavior and never seemed able to get back to a good state again):

![image](https://user-images.githubusercontent.com/10023676/91360708-ccd29c80-e7ab-11ea-9e9f-d7248da0b17b.png)

Is there some strange magic happening behind the scenes that is causing the fix to disappear? Is there anything I can do to help diagnose?

**Comment by sharwell** [comment] 2020-09-06 19:23
The third image shows a code fix for SA1206, while the first two images show SA1201. Can you clarify which diagnostics you are expecting to be able to fix?

**Comment by sharwell** [comment] 2020-09-06 19:33
Duplicate of #1869

**Comment by sharwell** [comment] 2020-09-06 19:34
@brphelps We were forced to disable the code fix for SA1201 due to a number of outstanding bugs. I marked this as a duplicate of the tracking issue to eventually enable it again.

**Closed by sharwell** 2020-09-06 19:33 UTC
