### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by chanusch** [DotNetAnalyzers/StyleCopAnalyzers#2651] opened 2018-04-05 09:11 UTC
Hi!

No bug from rules, but the link on the very last section which routes to the already implemented rules is broken.

See here and scroll down to the bottom.
https://github.com/DotNetAnalyzers/StyleCopAnalyzers

Link goes to a default apache site.

Would be nice if this is working again.

Cheers!

**Comment by sharwell** [comment] 2018-04-05 20:34
Duplicate of #2569

**Closed by sharwell** 2018-04-05 20:34 UTC
