### ISSUE TITLE
SA1011 - Issue with nullable arrays

### ISSUE THREAD

**Issue by DrGriff** [DotNetAnalyzers/StyleCopAnalyzers#3219] opened 2020-10-08 14:06 UTC
Using `<PackageReference Include="StyleCop.Analyzers" Version="1.1.118">`, with a .Net Core 3.1 project with nullables enabled (`<Nullable>enable</Nullable>`).

The following code:
```
byte[]? byteData = null;
```
generates the following:

> Error	SA1011	Closing square bracket should be followed by a space.

I think this is a false positive.

**Comment by sharwell** [comment] 2020-10-08 14:25
Duplicate of #2927

**Closed by sharwell** 2020-10-08 14:25 UTC
