### ISSUE TITLE
SA1205 wrongfully identifies the lack of access modifier and suggests a wrong fix

### ISSUE THREAD

**Issue by paulomorgado** [DotNetAnalyzers/StyleCopAnalyzers#2524] opened 2017-08-25 14:00 UTC
![image](https://user-images.githubusercontent.com/470455/29717179-1a5ec3be-89a6-11e7-85c8-51e8028845d9.png)

**Comment by sharwell** [comment] 2017-08-26 18:11
:arrow_right: Ah, duplicate of #2040.

**Closed by sharwell** 2017-08-26 18:11 UTC
