### ISSUE TITLE
SA1119 is incorrect when negating the result of the 'is' operator

### ISSUE THREAD

**Issue by KevinZinn** [DotNetAnalyzers/StyleCopAnalyzers#2767] opened 2018-08-28 20:19 UTC
I've run into this issue several times, where i use the following statement:
`if (!(x is SomeType y))`

SA1119 recommends `if (!x is SomeType y)`, which is not valid C# code

**Comment by sharwell** [comment] 2018-08-28 20:50
Duplicate of #2372

**Closed by sharwell** 2018-08-28 20:50 UTC
