### ISSUE TITLE
False Positive: SA1000 reports on target-typed new expressions

### ISSUE THREAD

**Issue by Corniel** [DotNetAnalyzers/StyleCopAnalyzers#3350] opened 2021-06-12 20:09 UTC
See: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/target-typed-new

``` C#
MyClass class = new();
```

Triggers a SA1000, claiming there should be a space after the new keyword.

**Comment by sharwell** [comment] 2021-06-14 13:57
Duplicate of #3214

**Closed by sharwell** 2021-06-14 13:57 UTC
