### ISSUE TITLE
SA1010 false positive when instantiating empty array

### ISSUE THREAD

**Issue by riley211** [DotNetAnalyzers/StyleCopAnalyzers#3821] opened 2024-04-04 12:09 UTC
See screenshot. Removing the space then raises SA1003.

![image](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/assets/108871396/a79d51b3-9981-4443-abd2-8f88b9dfc851)

**Comment by bjornhellander** [comment] 2024-04-05 04:54
This should go away if you switch to the latest beta.

**Comment by bjornhellander** [comment] 2024-04-05 04:55
Duplicate of  #3687

**Closed** 2024-04-05 14:00 UTC

**Comment by nolme** [comment] 2024-12-27 18:53
We're nearly in 2025, is there a release coming soon ?
