### ISSUE TITLE
stylecop rule that corresponds to the resharper namespace resolver

### ISSUE THREAD

**Issue by jimmymain** [DotNetAnalyzers/StyleCopAnalyzers#1522] opened 2015-09-21 11:55 UTC
Hi,

Resharper already has a built in fix for [namespace and file locations](http://confluence.jetbrains.com/display/ReSharper/Namespace+does+not+correspond+to+file+location)
Stylecop should possibly have a similar enforceable rule?

**Comment by sharwell** [comment] 2015-09-21 12:40
This looks like a duplicate of #1481. Can you confirm? :smile:

**Comment by Maxwe11** [comment] 2015-09-21 12:56
it's dup

**Closed** 2015-09-21 12:56 UTC
Labels: duplicate
