### ISSUE TITLE
SA1210 and SA1208 does not play nice when global:: prefix is used

### ISSUE THREAD

**Issue by dmitriyse** [DotNetAnalyzers/StyleCopAnalyzers#1818] opened 2015-11-23 21:19 UTC
![image](https://cloud.githubusercontent.com/assets/10322215/11350105/55b37262-9249-11e5-8a68-60c46b749d0e.png)

**Comment by sharwell** [comment] 2015-11-23 21:43
This is a duplicate of #1092.

**Comment by dmitriyse** [comment] 2015-11-23 22:13
Please think not only about pure VS users, but also about R# users + StyleCop Plugin.
Possibly some options should introduced to satisfy all useres.

**Comment by sharwell** [comment] 2015-11-23 23:16
An option might make sense. For the default behavior, it makes sense to adhere to Visual Studio defaults as they are the majority of users.

Fortunately this particular situation is quite rare.

**Comment by sharwell** [comment] 2015-11-23 23:50
@dmitriyse Is there a reason you are using the StyleCop Plugin for ReSharper, as opposed to the code fixes which are provided by this project?

I invited you to our Gitter chat room if you'd like to discuss it with us there.

**Comment by sharwell** [comment] 2015-12-03 14:47
@dmitriyse Reported that there is *no* ordering of the directives shown above which does not report either SA1208 or SA1210.

**Closed** 2015-12-04 17:06 UTC
Labels: bug, fixed
