### ISSUE TITLE
SA1119 is broken with pattern matching

### ISSUE THREAD

**Issue by nicholassuter** [DotNetAnalyzers/StyleCopAnalyzers#2570] opened 2017-11-29 16:45 UTC
This statement generates a violation of SA1119

```csharp
var x = new object();
if (!(x is int i))
    throw new Exception("Woopsie");
Console.WriteLine("is an int");
```

The proposed fix is 

```csharp
var x = new object();
if (!x is int i)
    throw new Exception("Woopsie");
Console.WriteLine("is an int");
```

This generates a CS0023 (Operator '!' cannot be applied to operand of type 'object') compiler error.

The workaround is disabling this rule (or not using the StyleCop analyzer...)

**Comment by TimSirmovics** [comment] 2017-11-29 22:00
I am also experiencing this issue.

This code triggers SA1119:

```
if (!(WebRequest.Create(fileUri) is FtpWebRequest ftpWebRequest))
    throw new InvalidLogicException("Cannot cast WebRequest as FtpWebRequest");
```

But removing the paranthesis changes the meaning of the code and causes a compiler error.

**Comment by vweijsters** [comment] 2017-12-10 10:53
@nicholassuter and @TimSirmovics: Which version of StyleCop.Analyzers produced this result? I've tried the provided examples with version 1.1.0-beta004 and that is working as intended, not producing any warnings.

**Comment by TimSirmovics** [comment] 2017-12-10 20:27
Latest stable, v1.0.2

**Comment by sharwell** [comment] 2018-01-17 17:01
Duplicate of #2372

**Closed by sharwell** 2018-01-17 17:01 UTC
Labels: bug, c# 7
