### ISSUE TITLE
SA1412 Encode as UTF8 with BOM quickfix breaks EF migrations

### ISSUE THREAD

**Issue by bexxx** [DotNetAnalyzers/StyleCopAnalyzers#2190] opened 2016-08-11 12:45 UTC
Hi,

my project had a lot of EF code first migrations. The files are not UTF8, so this rule fired.
I selected the fix and applied it to the whole project and it breaks the functionality (unfortunately you don't see this right away, because everything still compiles...

A single migration is stored as three files on disk:
201509271450527_AddAzureURIAcousticDataSets.cs
201509271450527_AddAzureURIAcousticDataSets.Designer.cs
201509271450527_AddAzureURIAcousticDataSets.resx

The issue is that the csproj with migrations looks like this:
...
<Compile Include="Migrations\201509271450527_AddAzureURIAcousticDataSets.cs" />
    <Compile Include="Migrations\201509271450527_AddAzureURIAcousticDataSets.Designer.cs">
      <DependentUpon>201509271450527_AddAzureURIAcousticDataSets.cs</DependentUpon>
    </Compile>
...

After the quick fix the files (*.Designer.cs & *.resx) are gone and the csproj only contains the *.cs file.

This is still valid code and you will only notice the issue when you try to connect to the database at runtime.

Very weird issue ..

**Comment by sharwell** [comment] 2016-08-11 12:59
:memo: Possibly a duplicate of #1239

**Closed** 2016-11-15 01:54 UTC
Labels: duplicate
