### ISSUE TITLE
SA1516 falsely triggers on top level statements 

### ISSUE THREAD

**Issue by DavidArno** [DotNetAnalyzers/StyleCopAnalyzers#3713] opened 2023-10-18 15:18 UTC
A Program.cs file containing the following:
```cs
using System;

var x = 1;
var y = 1;
var z = 1;

Console.WriteLine((x, y, z));
```
Results in `SA1516` being reported for the `var y = 1;` and `var z = 1;` lines.

**Comment by bjornhellander** [comment] 2023-11-10 17:48
I can not reproduce this. Looks like a duplicate of #3351.

You need to use a beta version if you are using a "late" c# version. This would for example probably happen if you use StyleCop 1.1.118, which is from 2019.

**Comment by sharwell** [comment] 2023-11-10 18:04
Duplicate of #3351

**Closed by sharwell** 2023-11-10 18:04 UTC
