### ISSUE TITLE
SA1629 should also accept other punctuation characters like '!' or '?' as valid line endings.

### ISSUE THREAD

**Issue by genxs-trading** [DotNetAnalyzers/StyleCopAnalyzers#3480] opened 2022-04-12 19:53 UTC
SA1629 should also accept other punctuation characters like '!' or '?' as valid line endings.

_Originally posted by @IngbertPalm in https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/2680#issuecomment-388158978_

**Comment by sharwell** [comment] 2022-04-18 19:38
Duplicate of #2724

**Closed by sharwell** 2022-04-18 19:38 UTC
Labels: duplicate
