### ISSUE TITLE
SA1313 does not handle record type members (C# 9.0)

### ISSUE THREAD

**Issue by onyxmaster** [DotNetAnalyzers/StyleCopAnalyzers#3244] opened 2020-11-17 16:06 UTC
Consider the following declaration:
```csharp
public record Asd(int Value);
```

Currently, StyleCop treats `Value` as a method parameter and attempts to enforce the associated naming rule, but this is actually a property name.

**Comment by sharwell** [comment] 2020-11-17 17:37
Duplicate of #3232

**Closed by sharwell** 2020-11-17 17:37 UTC
