### ISSUE TITLE
Consider supporting Settings.Stylecop or other configuration

### ISSUE THREAD

**Issue by wekempf** [DotNetAnalyzers/StyleCopAnalyzers#1045] opened 2015-07-25 19:34 UTC
There are some things from StyleCop that pretty much requires supporting some configuration. For instance, spell checking needs dictionary support, and prefix rules for names often require ways to exclude some prefixes.

There's tension in supporting the existing configuration file, because that would mean there's two places where you can control the severity of individual rules. However, it would also mean you could control this at the solution level instead of the project level, which would be nice. In any case, just supporting some form of config file would be useful. For instance, issue [10390](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/1039) is another case where being able to specify which files to exclude would be useful, and would allow you to keep very conservative hard coded rules for detecting generated files, while allowing individuals the ability to specify a "more complete" file filter.

**Comment by sharwell** [comment] 2015-07-26 02:50
This is a duplicate of #892 and/or #422.

**Closed by sharwell** 2015-07-26 02:50 UTC
