### ISSUE TITLE
c# 9 record raise SA1649FileNameMustMatchTypeName

### ISSUE THREAD

**Issue by luboid** [DotNetAnalyzers/StyleCopAnalyzers#3300] opened 2021-02-12 12:40 UTC
Package=StyleCop.Analyzers
Version=1.1.118

Code:

```c#
    public record ChannelNumber
    {
        public Channel Channel { get; set; }

        public string Number { get; set; }
    }
```

Exception:

```
CSC : warning AD0001: Analyzer 'StyleCop.Analyzers.DocumentationRules.SA1649FileNameMustMatchTypeName' threw an exception of type 'System.ArgumentException' with message 'Unhandled declaration kind: RecordDeclaration'.
```

![image](https://user-images.githubusercontent.com/383517/107768988-f2deff80-6d3f-11eb-8b9d-202b2216b17e.png)

**Comment by sharwell** [comment] 2021-02-12 18:25
Duplicate of #3213

**Closed by sharwell** 2021-02-12 18:25 UTC
