### ISSUE TITLE
Need rule to catch constants in parameters

### ISSUE THREAD

**Issue by iSazonov** [DotNetAnalyzers/StyleCopAnalyzers#2683] opened 2018-05-11 12:33 UTC
Using constants in parameters creates obscure code:
```c#
EnumerateDirectory(true, 2);
```
Recomendation is to use named parameters:
```c#
EnumerateDirectory(Recurce: true, Depth: 2);
```

**Comment by sharwell** [comment] 2018-05-11 15:15
Duplicate of #2220

**Closed by sharwell** 2018-05-11 15:15 UTC
Labels: needs discussion, proposal
