### ISSUE TITLE
False positive SA1015 when using generic attribute 

### ISSUE THREAD

**Issue by genxs-trading** [DotNetAnalyzers/StyleCopAnalyzers#3686] opened 2023-08-10 13:43 UTC
`[DescriptionFromXmlDoc<MyType>]`

Triggers **SA1015: Closing generic bracket should be followed by a space**.

**Comment by bjornhellander** [comment] 2023-08-12 05:49
I can't reproduce this. Looks like a duplicate of #3487.

If you want to use newer language constructs, you need to use the beta versions, since 1.1.118 is old. See for example #3500 for an explanation of why.

**Comment by sharwell** [comment] 2023-08-15 13:38
Duplicate of #3487

**Closed by sharwell** 2023-08-15 13:38 UTC
Labels: c# 11
