### ISSUE TITLE
SA1200	Using directive should appear within a namespace declaration

### ISSUE THREAD

**Issue by daleao** [DotNetAnalyzers/StyleCopAnalyzers#3825] opened 2024-04-12 04:10 UTC
Conflicts with *[CS8914](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/using-directive-errors?f1url=%3FappId%3Droslyn%26k%3Dk%28CS8914%29#global-using-directive) Error: A global using directive cannot be used in a namespace declaration.*

**Comment by bjornhellander** [comment] 2024-04-12 05:14
Could you provide an example so your situation is clear?

**Comment by daleao** [comment] 2024-04-12 16:50
I thought it was clear but sure...

This causes SA1200:
```cs
global using static Foo.Bar;

namespace Foo;

using System;
```

This causes CS8914:
```cs
namespace Foo;

global using static Foo.Bar;
using System;
```

SA1200 is incorrectly applying to global using statements, which cannot be placed within namespaces.

**Comment by bjornhellander** [comment] 2024-04-12 19:08
Duplicate of #3404 (still open)

**Closed** 2024-04-15 15:50 UTC
