### ISSUE TITLE
SA1206 conflicts with IDE0036 for required properties

### ISSUE THREAD

**Issue by symbiogenesis** [DotNetAnalyzers/StyleCopAnalyzers#3592] opened 2023-01-08 20:42 UTC
SA1206 wants _required_ to come before the accessibility keyword. But IDE0036 wants the reverse.

https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0036

Affects version: 1.2.0-beta.435

**Comment by bjornhellander** [comment] 2023-01-11 21:10
Duplicate of #3527

**Closed** 2023-02-09 20:35 UTC
