### ISSUE TITLE
GeneratedCodeAttribute not supported for skipping analysis

### ISSUE THREAD

**Issue by geoarion** [DotNetAnalyzers/StyleCopAnalyzers#1342] opened 2015-08-31 11:12 UTC
It seems the GeneratedCodeAttribute attribute is ignored currently by the StyleCop Analyzers.

Looking at: https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/3253066a70adea61baa6a03c1dd99943da9cd8fe/StyleCop.Analyzers/StyleCop.Analyzers/GeneratedCodeAnalysisExtensions.cs it seems that the only way to skip analysis is done at a file level with the "<autogenerated" text being expected in header of the file or if the file is empty or if the file name has "designer" in the name.

Is there any plan to support the GeneratedCodeAttribute on class-by-class basis for skipping?

**Comment by sharwell** [comment] 2015-08-31 12:56
Hi @geoarion and welcome to the project. :smile: 

This is a duplicate of #1094. Please open a new issue if you continue to run into specific problems with the exclusions.

**Closed** 2015-08-31 13:37 UTC
Labels: duplicate

**Comment by geoarion** [comment] 2015-08-31 18:41
Sorry for missing the existing item and thanks, Sam!

**Comment by sharwell** [comment] 2015-08-31 19:37
@geoarion No problem at all! I definitely prefer duplicates to people not bothering to come talk to us. :smile:
