### ISSUE TITLE
specify locale for rules like 1642

### ISSUE THREAD

**Issue by jimmymain** [DotNetAnalyzers/StyleCopAnalyzers#1339] opened 2015-08-31 06:51 UTC
Hi,

The original/current stylecop supported setting the locale to en-GB in the settings file.
This correctly spelled initiali**z**es as initiali**s**es when the locale settings in the stylecop settings file were set to en-GB.

In the meantime: I will change all my code to American :-)

**Comment by sharwell** [comment] 2015-08-31 12:53
Duplicate of #1143.

**Closed by sharwell** 2015-08-31 12:53 UTC
