### ISSUE TITLE
SA1200 "Reorder using statements" code fix uses spaces to indent instead of tabs

### ISSUE THREAD

**Issue by AArnott** [DotNetAnalyzers/StyleCopAnalyzers#3129] opened 2020-03-18 18:48 UTC
When .editorconfig indicates that tabs should be used, the SA1200 code fix still uses spaces, not only for the moved using but it re-indents all the existing using statements that were already in proper positions using spaces.

StyleCop.Analyzers version: 1.2.0-beta.164

**Comment by sharwell** [comment] 2020-09-26 22:26
StyleCop Analyzers code fixes use the spacing settings from **stylecop.json**, not the ones from **.editorconfig**. The default if not specified is 4 spaces. We have an open issue covering high-level support for **.editorconfig** when **stylecop.json** is missing or under-specified.

**Comment by sharwell** [comment] 2020-09-26 22:27
Duplicate of #2745

**Closed by sharwell** 2020-09-26 22:27 UTC
Labels: bug, up for grabs
