### ISSUE TITLE
SA1313 incorrectly suggests that record property names should start with a lower-case letter.

### ISSUE THREAD

**Issue by mrudat** [DotNetAnalyzers/StyleCopAnalyzers#3845] opened 2024-05-19 08:32 UTC
```cs
[SuppressMessage("StyleCop.CSharp.NamingRules", "SA1313:Parameter names should begin with lower-case letter", Justification = "Property names should begin with upper-case letter")]
public record SomeRecord(string SomeString, int SomeInteger)
{
}
```

**Comment by bjornhellander** [comment] 2024-05-19 12:13
Which version are you using?

**Comment by bjornhellander** [comment] 2024-05-19 14:13
I am unable to reproduct this with the latest beta

**Comment by sharwell** [comment] 2024-05-21 13:19
Duplicate of #3181

**Closed by sharwell** 2024-05-21 13:19 UTC
