### ISSUE TITLE
Rule SA1008 should add => for expression based properties/functions as exception

### ISSUE THREAD

**Issue by jongleur1983** [DotNetAnalyzers/StyleCopAnalyzers#2521] opened 2017-08-21 12:23 UTC
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1008.md is defined as:
"A violation of this rule occurs when the opening parenthesis within a statement is not spaced correctly. An opening parenthesis should not be preceded by any whitespace, unless it is the first character on the line, or it is preceded by certain C# keywords such as if, while, or for. In addition, an opening parenthesis is allowed to be preceded by whitespace when it follows an operator symbol within an expression."

I suggest to add "=>" to the list of exceptions to allow spaces before opening paranthesis in source like

`x.Select(item => (item.X, item.Z))`

in this case a value tuple is returned, but it could be a paranthesis from a calculation expression as well as in 

`x.Select(number => (number + 3) * 20)`

**Comment by sharwell** [comment] 2017-08-21 14:33
:question: is SA1008 currently being reported in this case, or is this just a documentation bug?

**Comment by jongleur1983** [comment] 2017-08-21 15:14
yes, SA1008 is reported, and we think that should not be the case.

**Comment by KlemensE** [comment] 2017-09-02 11:26
I could not reproduce the problem you mentioned. Are my code examples correct for the issue you reported?

**Comment by vweijsters** [comment] 2017-09-03 15:09
The tuple expression is not handled correctly by versions 1.0.0 and 1.0.2, which is logical, as they don't have support for C# 7. Version 1.1.0-beta004 produces correct results.

The parenthesized expression produces correct results in 1.0.0, 1.0.2 and 1.1.0-beta004.

Closing this issue as fixed.

**Closed by vweijsters** 2017-09-03 15:09 UTC
Labels: bug, fixed
