### ISSUE TITLE
SA1624 should treat read-only properties the same way as properties with private setters.

### ISSUE THREAD

**Issue by pfattisc** [DotNetAnalyzers/StyleCopAnalyzers#2755] opened 2018-08-20 12:15 UTC
SA1624 does not complain about the summary of _Bar_ in the following code example:
```
public class Foo
{

  public Foo(int bar)
  {
    this.Bar = bar;
  }

///<summary>Gets or sets the Bar.</summary>
 public int Bar { get; }
}
```

I would expect that the analyzer would issue the summary of _Bar_  as it does for a Bar property with a private setter:
```
public int Bar { get; private set; }
}
```

***Tested with Stylecop Analyzer v1.0.2.***

**Comment by sharwell** [comment] 2018-08-20 17:01
:+1:

**Comment by sharwell** [comment] 2018-09-03 22:10
Duplicate of #2253

**Closed by sharwell** 2018-09-03 22:10 UTC
Labels: bug, up for grabs
