### ISSUE TITLE
Visual Studio 2015 community edition RC crash while try to view warning analyzed by StyleCop

### ISSUE THREAD

**Issue by smartcodingxx** [DotNetAnalyzers/StyleCopAnalyzers#1015] opened 2015-07-21 12:10 UTC
Replication procedure 
Step 1. Build the C# code
Step 2. Double click on the any one warning from list to open c# code.
Step 3. Click on small down icon ( besides bulb sign indication) on the left side of warning in C# code.
            This will crash the whole Visual Studio 2015 community edition RC

Thanks,
Dharmendra

**Comment by sharwell** [comment] 2015-07-21 12:18
Hi @smartcodingxx,

I'm sorry to hear you are running into problems with this. Can you check which version of StyleCopAnalyzers you have installed in your project? You will want version 1.0.0-Alpha011, since that is the last version that supports the RC release of Visual Studio 2015. If you still run into problems, try using 1.0.0-alpha010 (it was used during development of StyleCopAnalyzers itself for about a month without anyone reporting this issue).

**Comment by smartcodingxx** [comment] 2015-07-23 09:17
Thanks Sharwell for reply,

I am using StyleCopAnalyzers 1.0.0-beta001 (Prerelease version).

Is there any possibility due to Prerelease version ?

I have installed it using built in nueget package manger. As StyleCopAnalyzers not showing if I not tick the "Include prerelease" in nueget window.

Let me know if you still want any information.

Dharmendra

**Comment by sharwell** [comment] 2015-07-23 12:21
Hi @smartcodingxx,

The problem is caused by using a pre-release version of Visual Studio (the RC release). If you want to use StyleCopAnalyzers with the RC release of Visual Studio, you will need to use the NuGet Package Manager to manually select the **1.0.0-alpha011** release; (the **1.0.0-beta001** release only supports the final release of Visual Studio 2015). The version selection is above step 5 in the image shown in the [installation section of our readme](https://github.com/DotNetAnalyzers/StyleCopAnalyzers#installation).

I'm going to close this as **wontfix**, since we are no longer doing any work with Visual Studio 2015 RC. If you continue to observe this problem after updating to the final release of Visual Studio 2015, please don't hesitate to reopen this issue. :smile:

**Closed by sharwell** 2015-07-23 12:21 UTC
Labels: bug

**Comment by smartcodingxx** [comment] 2015-07-27 13:05
Hi Sharewell,

Thanks for pointing out. Downgrade to <b> 1.0.0-alpha011 </b> fix the issue.

Will surely open this again if it happen in final release of Vs2012.

Thanks for listening,  :smile:
Dharmendra
