### ISSUE TITLE
SA1313 should not be rised when parameter is in record constructor

### ISSUE THREAD

**Issue by AdamWyzgol** [DotNetAnalyzers/StyleCopAnalyzers#3304] opened 2021-02-20 09:14 UTC
Such syntax 
`record RecordName(string ParamA, int ParamB); `
should not match SA1313 rule.

**Comment by AdamWyzgol** [comment] 2021-02-20 09:20
sorry, missed that this is working in beta version, when it will be stable? we use records in production and don't want any beta dependencies.

**Comment by sharwell** [comment] 2021-02-20 18:37
> don't want any beta dependencies

StyleCop Analyzers isn't a shipping dependency, so it doesn't fall into the same NuGet package analysis restrictions that other pre-release packages fall into. If you are just trying to check off a box saying there are no NuGet packages in the build with a `-beta` suffix, you can reference [StyleCop.Analyzers.Unstable 1.2.0.321](https://www.nuget.org/packages/StyleCop.Analyzers.Unstable/1.2.0.321) instead of [StyleCop.Analyzers 1.2.0-beta.321](https://www.nuget.org/packages/StyleCop.Analyzers/1.2.0-beta.321). Both packages are published at the same time.

**Comment by sharwell** [comment] 2021-02-20 18:38
Duplicate of #3232

**Closed by sharwell** 2021-02-20 18:38 UTC

**Comment by AdamWyzgol** [comment] 2021-02-20 18:41
maybe that information shoud be added to "C# language versions" in readme?
