### ISSUE TITLE
SA1005 is unaware of XML comments

### ISSUE THREAD

**Issue by RalfKoban** [DotNetAnalyzers/StyleCopAnalyzers#1048] opened 2015-07-26 09:01 UTC
Hi,

when I run the StyleCop analyzers (1.0.0.-beta001), I get an SA1005 reported for following code:

    /// <summary>
    /// Provides some stuff.
    /// </summary>

It looks like SA1005 is not aware of such XML comments.

**Comment by sharwell** [comment] 2015-07-26 13:45
Hi @RalfKoban,

Welcome to the project. :smile: This particular issue is a duplicate of #1012, and a fix for it will be included in the next release.

:memo: If you are seeing this problem, it means your project is not configured to check the semantics of XML documentation comments when you compile your code. It's likely that some of them contain incorrect syntax as a result; I strongly encourage correcting your project configuration as described in the comments of #1012. Normally this would enable some new warnings that people might not want, but my example in the comments directly addresses that. :+1:

**Closed by sharwell** 2015-07-26 13:45 UTC
