### ISSUE TITLE
SA1011 misfires on nullable ref type: `object[]?`

### ISSUE THREAD

**Issue by AArnott** [DotNetAnalyzers/StyleCopAnalyzers#2989] opened 2019-08-19 03:30 UTC
When using C# `#nullable enable` syntax, the following type is valid: `object[]?`. Yet SA1011 misfires wherever this type appears:

```cs
object[]? v;
```

> Warning	SA1011	Closing square bracket should be followed by a space.

**Comment by sharwell** [comment] 2019-09-03 03:09
Duplicate of #2927

**Closed by sharwell** 2019-09-03 03:09 UTC
Labels: c# 8.0
