### ISSUE TITLE
EntityFramework Core migrations not being ignored.

### ISSUE THREAD

**Issue by penkin** [DotNetAnalyzers/StyleCopAnalyzers#2555] opened 2017-11-06 15:20 UTC
I am not sure what is going on but I am getting the following errors when building a dotnet core 2.0 app;

-   20171102121558_Initial.Designer.cs(17, 33): [CS1591] Missing XML comment for publicly visible type or member 'Initial.BuildTargetModel(ModelBuilder)'
-   20171102121558_Initial.cs(9, 26): [CS1591] Missing XML comment for publicly visible type or member 'Initial'
-   20171102121558_Initial.cs(11, 33): [CS1591] Missing XML comment for publicly visible type or member 'Initial.Up(MigrationBuilder)'
-   20171102121558_Initial.cs(236, 33): [CS1591] Missing XML comment for publicly visible type or member 'Initial.Down(MigrationBuilder)'

On all of these files has `// <auto-generated />` on the first lines of the file put there by EntityFramework Core.

From what I understand the Analyzers should be ignoring these files? Am I missing something? I am using StyleCop.Analyzers 1.0.2. I have tried version 1.1.0-beta0004 as well with no success.

**Comment by penkin** [comment] 2017-11-06 15:22
My `stylecop.json` looks like this;

```
{
  "$schema": "https://raw.githubusercontent.com/DotNetAnalyzers/StyleCopAnalyzers/master/StyleCop.Analyzers/StyleCop.Analyzers/Settings/stylecop.schema.json",
  "settings": {
    "documentationRules": {
      "companyName": "Lombard Insurance Company",
      "copyrightText": "Copyright (c) {companyName}. All rights reserved. ",
      "xmlHeader": true,
      "fileNamingConvention": "metadata"
    },
    "namingRules": {
      "allowedHungarianPrefixes": [ "as", "do", "id", "if", "in", "is", "my", "no", "on", "to", "ui" ]
    }
  }
}
```

**Comment by sharwell** [comment] 2017-11-06 17:13
This is a duplicate of #1867. Specific guidance to address the situation can be found in https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/1867#issuecomment-160696004. :smile:

**Closed by sharwell** 2017-11-06 17:13 UTC

**Comment by penkin** [comment] 2017-11-07 09:57
Thanks. Sorted.
