### ISSUE TITLE
SA1009 : Rule does not work correctly with C#7 Tuples returned in a task

### ISSUE THREAD

**Issue by tommyhawk520** [DotNetAnalyzers/StyleCopAnalyzers#2693] opened 2018-05-22 09:42 UTC
When a method has a return type of a tuple using the C#7 syntax...

`public async Task<(string string1, string string2)> method(string string1)`

you get a warning that Closing parenthesis must be spaced correctly. If you put a space it then triggers SA1015 but it should work without a space so the rule will need updating to allow parenthesis without a trailing space when used within a task

**Comment by sharwell** [comment] 2018-05-22 13:05
Duplicate of #2537

**Closed** 2018-05-22 13:05 UTC
