### ISSUE TITLE
False Positive on SA1122 for switch expression

### ISSUE THREAD

**Issue by DrGriff** [DotNetAnalyzers/StyleCopAnalyzers#3199] opened 2020-09-18 10:44 UTC
Getting false positive for:
```
internal static AnEnum StringToEnumExample(this string s)
        {
            return s switch
            {
                "A valid string" => AnEnum.Valid,
                "" => AnEnum.None,
                null => AnEnum.None,
            };
        }
```
The second entry `""` is marked as a violation.  But if swap to `string.Empty` then this violates CS0150 where the switch expression requires a constant value.

Affects .Net Core 3.1 (and I guess .Net 5)

**Comment by sharwell** [comment] 2020-09-26 21:19
Duplicate of #3028

**Closed by sharwell** 2020-09-26 21:19 UTC
Labels: bug, duplicate, c# 8
