### ISSUE TITLE
Proposed exception to SA1025

### ISSUE THREAD

**Issue by lcsondes** [DotNetAnalyzers/StyleCopAnalyzers#2842] opened 2018-12-28 10:48 UTC
SA1025 doesn't trigger if the line otherwise ends with a semicolon, so you can have

    Foo();    // aligned comments
    BarBar(); // like this

Properties share this scenario, but they don't end with a semicolon:

    int Foo { get; set; }    // aligned
    int BarBar { get; set; } // comments

Depending on personal style, one might want to align the braces to the property names, which is another exception that could be considered.

**Comment by sharwell** [comment] 2019-01-06 03:12
I am generally against end-of-line comments that follow code. I also find that the primary outcome of intra-line alignment is maintenance nightmares, so I would generally be against making an exception here.

I'll leave the issue open so others can comment.

**Comment by lcsondes** [comment] 2019-01-07 12:34
I could get behind it not being allowed anywhere but given that there's already an exception for one case, not having it for another similar case is inconsistent.

**Comment by sharwell** [comment] 2019-01-07 13:39
The current exception was added because StyleCop Classic included the exception, and we didn't want to cause additional problems for users switching from that set of analyzers to StyleCop Analyzers. 😄

**Comment by sharwell** [comment] 2023-08-07 13:57
Duplicate of #1424

**Closed by sharwell** 2023-08-07 13:57 UTC
Labels: needs discussion
