### ISSUE TITLE
SA1313: Gets applied to record positional parameters

### ISSUE THREAD

**Issue by Timo-Weike** [DotNetAnalyzers/StyleCopAnalyzers#3451] opened 2022-02-04 08:11 UTC
If one defines a record like 
~~~ cs
public record SomeName(string Name);
~~~
StyleCop complains about the `Name` parameter, but since defined like this the name of the parameter becomes the name of the
public property for that value. So this needs to be written with an upper-case letter.

Even according to the [Microsoft coding convention](https://github.com/mrrogercampbell/microsoft-codecamp-lecture-notes/blob/main/resources/microsofts-csharp-coding-conventions.md#:~:text=When%20writing%20positional%20records%2C%20use%20pascal%20casing%20for%20parameters%20as%20they%27re%20the%20public%20properties%20of%20the%20record.) should this be written with an upper-case letter.

**Comment by sharwell** [comment] 2022-02-04 14:46
Duplicate of #3181

**Closed by sharwell** 2022-02-04 14:46 UTC
