### ISSUE TITLE
SA1025 - Strict on single return statement

### ISSUE THREAD

**Issue by BeakerAU** [DotNetAnalyzers/StyleCopAnalyzers#2508] opened 2017-08-01 06:50 UTC
SA1025 reports the following as a failure (when it passed in StyleCop Classic):

`if (condition) return true;`

It would be good if this condition/structure could be added as an exception for SA1025. I couldn't find it listed in KnownChanges.md as a difference.

**Comment by vweijsters** [comment] 2017-08-01 11:35
Hi,
I've just checked and StyleCop Classic (4.7.49.0) does not report SA1025 for the given statement. It does produce SA1503. I've also verified that StyleCop.Analyzers produces the same warning.

Could you please provide more details on what the problem / question is? Are you asking us to relax SA1503 to allow single line return statements as an option?

**Comment by BeakerAU** [comment] 2017-08-01 23:06
My apologies, @vweijsters.
I would like SA1025 to be relaxed in this situation, to allow a condition + break/continue/return/throw statement to be on a single line.
We don't run SA1503 as part of our ruleset.

**Comment by sharwell** [comment] 2017-08-01 23:17
@BeakerAU Are you certain the reported warning is SA1025? That warning makes no sense for the example. Also I'm not able to reproduce the behavior you describe with 1.1.0-beta004. Can you verify that your code sample matches your scenario?

**Comment by BeakerAU** [comment] 2017-08-01 23:32
Sorry @sharwell - I must have written the wrong number in the heading, then assumed that that was correct. The warningis being raised under [SA1501](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1501.md), not SA1025.

**Comment by sharwell** [comment] 2017-08-02 04:00
Ah, that makes more sense. This looks like a duplicate of #2252.

**Closed by sharwell** 2017-08-02 04:00 UTC
Labels: question
