### ISSUE TITLE
Enabling SX1309FieldNamesMustBeginWithUnderscore via .editorconfig doesn't work

### ISSUE THREAD

**Issue by cosminstirbu** [DotNetAnalyzers/StyleCopAnalyzers#3039] opened 2019-10-14 12:27 UTC
Hello,

I've added the following entry in .editorconfig

```
# SX1309: Fields must begin with underscore
dotnet_diagnostic.SX1309.severity = warning
```

I am expecting that any private fields that don't have the _ prefix would cause an warning, but unfortunately it doesn't.

If I configure it via a .ruleset file then it works :-?

I'm using version 1.1.118

Thanks,
Cosmin

**Comment by sharwell** [comment] 2019-10-14 16:09
Duplicate of dotnet/roslyn#38792

**Closed by sharwell** 2019-10-14 16:09 UTC
