### ISSUE TITLE
SA1107 Round Tripping Fix Does Not Correct Violation

### ISSUE THREAD

**Issue by aolszowka** [DotNetAnalyzers/StyleCopAnalyzers#2862] opened 2019-01-30 23:16 UTC
Utilizing the provided StyleCopTester.exe (this tool is very strong/awesome by the way thank you) and after putting it in CI under our code base a single file kept popping out; the resulting format resulted in no changes which may indicate an issue with SA1107's Fix.

I stripped down our utility program to the bare minimum and ran the trouble file through Delta Debugging (https://www.st.cs.uni-saarland.de/dd/) using this utility which produced this nonsensical minimal test case, any removal of any character in this file will cause it to pass.

```csharp
d({{};
```

Using the minimal test case I worked it backwards to produce a more readable scenario:

```csharp
namespace SA1107Bug
{
    class Program
    {
        //Minimal TestCase d({{};
        static void Main(string[] args)
        {
            {
                System.Console.WriteLine("Test");
            };
        }
    }
}
```

Line 10 triggers SA1107 using StyleCop.Analyzers 1.0.2 from NuGet.org but as you can see attempting to preview the fix results in no fixes available:

![image](https://user-images.githubusercontent.com/2592881/52019088-ed405500-24a9-11e9-9ca2-cc9e3c10cb6c.png)

It looks like some work was done to fix some corner cases under #1543 but it is unclear if this is related.

**Comment by sharwell** [comment] 2019-02-18 20:29
Interesting. This appears to be a bug in Roslyn's formatter. It would be possible to work around the issue in this code fix, but also tedious and potentially introduce other bugs. Given that the preferred fix for this issue is fixing SA1106 (removing the unnecessary empty statement), it seems safe to document the current behavior via a unit test and resolve the issue as **wontfix**.

**Comment by vweijsters** [comment] 2019-02-18 23:22
I can't reproduce this with 1.1.1-rc.101

**Comment by aolszowka** [comment] 2019-02-18 23:28
@vweijsters I am still able to repo it in 1.1.1-rc.101 available from NuGet; are you sure you copied and pasted the example as shown? Including the closing ; which as @sharwell points out is a violation of SA1106; removal of that line will fix the bug.

At the end of the day I am OK with a wontfix; is this worth reporting upstream to roslyn? Can you expand upon that bug more?

**Comment by vweijsters** [comment] 2019-02-19 19:57
I tried it again and now I can reproduce it as well. Don't know what I did wrong last time.

**Closed** 2019-02-19 21:03 UTC
Labels: bug, external, pull request
