### ISSUE TITLE
SA1313 false positive for chained lambdas with discards

### ISSUE THREAD

**Issue by djfr** [DotNetAnalyzers/StyleCopAnalyzers#3017] opened 2019-09-04 11:42 UTC
Tested with `StyleCop.Analyzers 1.1.118`

Reproduction:

```c#
var action = new Action<string, string>((_, __) =>
{
    var innerAction = new Action<string, string>((___, ____) => { }); // false SA1313
});
```

**Comment by sharwell** [comment] 2019-09-05 04:27
This is covered by https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/1606#issuecomment-365563606 and https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/1606#issuecomment-415463606. 😄

**Comment by sharwell** [comment] 2019-09-05 04:27
Duplicate of #1606

**Closed by sharwell** 2019-09-05 04:27 UTC
