### ISSUE TITLE
SA1013 in collision with SA1010 (closing braces vs opening square brackets)

### ISSUE THREAD

**Issue by veljkoz** [DotNetAnalyzers/StyleCopAnalyzers#3175] opened 2020-07-24 20:56 UTC
In the following statement:

`new[] { 1, 2, 3 } [new Random().Next(2)]`

One cannot reconcile the two rules - the closing braces after number 3 requires a space, opening bracket requires no space.

**Comment by sharwell** [comment] 2020-07-24 20:59
Duplicate of #1657

**Closed by sharwell** 2020-07-24 20:59 UTC
