### ISSUE TITLE
SA1402 doesn't recognize records

### ISSUE THREAD

**Issue by Arthri** [DotNetAnalyzers/StyleCopAnalyzers#3852] opened 2024-05-29 15:31 UTC
The following does not trigger SA1402 "file may only contain a single type", when it should
```cs
namespace Z
{
    internal record class X
    {
    }

    internal class Y
    {
    }
}
```

**Comment by bjornhellander** [comment] 2024-05-29 18:21
I can not reproduct this, using the latest version (1.2.0-beta.556).
What version are you using?

**Comment by bjornhellander** [comment] 2024-05-29 18:33
That one is from 2019 and has obvious problems with new language features. The recommendation is to use the latest beta version if you want to use modern c#.

**Comment by bjornhellander** [comment] 2024-05-29 19:09
Duplicate of #3542

**Closed as not planned** 2024-05-30 03:29 UTC
Labels: duplicate
