### ISSUE TITLE
SA1649 reports mismatched filename for typename incrrectly for generic type

### ISSUE THREAD

**Issue by rkeithhill** [DotNetAnalyzers/StyleCopAnalyzers#1729] opened 2015-11-04 22:39 UTC
I could be wrong here but it seems that it should be OK to have a filename of `Foo.cs` for typename `Foo<T>`.

**Comment by rkeithhill** [comment] 2015-11-05 15:37
Another option is to split this rule two - one for non-generic types and another rule for generic types but it would be nice if the non-generic rule still enforced that Foo<T> was in a file called Foo.cs (and not Bar.cs).

**Comment by sharwell** [comment] 2015-11-07 20:15
@rkeithhill We are currently investigating this issue as a deviation from StyleCop Classic (which gives it "special" status) in #1730. I'm going to mark this as a duplicate of the content in #1662 and #1730.

**Closed by sharwell** 2015-11-07 20:15 UTC
