### ISSUE TITLE
SA1633 Context menus appear when rule is Disabled

### ISSUE THREAD

**Issue by jeremyregnerus** [DotNetAnalyzers/StyleCopAnalyzers#3679] opened 2023-07-21 21:58 UTC
After disabling SA1633, StyleCop still presents the options `Add StyleCop setting file to the project` and `Add file header` to the Intellisense context menu. I'm more-so looking for a way to disable these menu items as I accidentally click them often. I do not use file headers, and I use .editorconfig to control all of my analyzer settings. However, I noticed both menus are both directly related to SA1633, so may be they should be hiding when this option is disabled.

This is the context menu items that still appear that I would like to disable.
![Context Menu](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/assets/7407481/c7ef890b-564a-46e4-adaf-ed0b39531891)
Both of these sub-menu items specifically call out SA1633.
![Add Settings File](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/assets/7407481/94997f74-22a1-472e-918a-ecd1365fbb13)
![Standard Header Message](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/assets/7407481/b437d371-4a10-43b1-98b7-1c138beec88d)

**Comment by bjornhellander** [comment] 2023-07-22 07:45
I am not seeing this behaviour. Can you provide a link to some code that reproduces this?

**Comment by bjornhellander** [comment] 2023-07-22 07:54
As far as I understand, this can't happen if you have disabled the rule properly. Is it possible that you have multiple projects and it is still active in some of them? Where is your .editorconfig located?

**Comment by jeremyregnerus** [comment] 2023-07-22 22:55
- I created a brand new solution (TestSolution), Added 2 Class Libraries named Project1 & Project2 each with 1 new class named Class1 & Class2 respectively.
- I added the NuGet package StyleCop.Analyzers.Unstable version 1.2.0.507.
- I then added a new .editorconfig file as a Solution Item **'1'**. I had to close and re-open the solution to get the .editorconfig file to populate the SA analyzers into the analyzers list in the .editorconfig menu.
- I then set rule SA1633 **'2'** to Disabled **'3'**
- Any warnings in my solution go away in the error list **'4'**
- However, the menus mentioned above still appear when I press `ctrl + .` or click the Quick Actions light bulb icon on either class **'5'**

![New Project](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/assets/7407481/b2fbd573-6b06-4abf-92a4-1ca4beb20a26)

**Comment by bjornhellander** [comment] 2023-07-23 07:34
Alright, now I see it too. I was disabling the rule by using "Configure or suppress issues"/"Configure SA1633 severity"/"None" in that same context menu. When doing that, the severity is set to "none" in the .editorconfig file, but if I instead double-click on the .editorconfig file and set it to Disabled, the severity is set to "silent" which in my opinion is not a good thing. Silent means that the rule is executed and the diagnostic is reported, but it is simply not shown to you. But code fixes are still offered for diagnostics with severity silent, so that is why you keep seeing it in the content menu. I would say that this is a bug either in the compiler or in Visual Studio.

**If you look at the .editorconfig file some other way (notepad, open with, etc), does it say "silent" for SA1633? If so, I hope that if you change silent to none, you will stop getting the context menu item about adding a header.**

You will still be able to get the context menu item for adding the settings file in some situations, but it should in that case mention another rule. The reason for this is that the code fix for adding the settings file is configured to trigger on more rules than SA1633.

**Comment by jeremyregnerus** [comment] 2023-07-23 13:26
This does remove the options from the quick actions, and definitely solves my immediate need. I would document this somewhere that the .editorconfig editor doesn't offer a way to set a value to none. Thank you for the help in resolving this. I'll let you decide what to do with this ticket as you opened the one above, and way want to wait for resolution on that.

**Comment by bjornhellander** [comment] 2023-07-25 06:12
Nice to hear that it worked!

**Comment by sharwell** [comment] 2023-07-25 13:58
Also note that severity configurations should be placed in .globalconfig, not .editorconfig. There is a significant UX gap related to this, and I believe currently it has to be done fully manually (and/or manually move all the lines from .editorconfig to .globalconfig after making changes).

**Comment by sharwell** [comment] 2023-07-25 13:58
Resolving as external

**Closed by sharwell** 2023-07-25 13:58 UTC
