### ISSUE TITLE
SA1206 has a problem with c# 11 required keyword

### ISSUE THREAD

**Issue by mehdihadeli** [DotNetAnalyzers/StyleCopAnalyzers#3627] opened 2023-04-02 14:32 UTC
Hi,
I get warring from `SA1206` rule when I use c# 11 `required` keyword. According to [Microsoft docs](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/required), it should be ok

``` csharp
public record Product
{
   public required decimal Price { get; init; }
}
```

**Comment by bjornhellander** [comment] 2023-04-02 15:33
Duplicate of #3527

**Closed** 2023-04-11 14:52 UTC
