### ISSUE TITLE
SA1011ClosingSquareBracketsMustBeSpacedCorrectly false-positive for nullable string arrays

### ISSUE THREAD

**Issue by DrGriff** [DotNetAnalyzers/StyleCopAnalyzers#3347] opened 2021-05-12 10:16 UTC
```
public string[]? MyProperty { get; set; }
```
This is a nullable string array and SA1011 states that the square bracket must be followed by a space, but this conflicts with SA1018NullableTypeSymbolsMustNotBePrecededBySpace.

**Comment by sharwell** [comment] 2021-05-12 13:27
Duplicate of #2927

**Closed by sharwell** 2021-05-12 13:27 UTC
