### ISSUE TITLE
SA1000 should allow target typed new() without space

### ISSUE THREAD

**Issue by chrfin** [DotNetAnalyzers/StyleCopAnalyzers#3367] opened 2021-07-08 12:58 UTC
[SA1000](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1000.md) should allow the target typed `new()` without a space in between the new and () as this is valid IMO. 

See: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/target-typed-new

**Comment by sharwell** [comment] 2021-07-08 16:48
Duplicate of #3214

**Closed by sharwell** 2021-07-08 16:48 UTC
Labels: duplicate
