### ISSUE TITLE
SA1008 makes use of C# 9 pattern match difficult

### ISSUE THREAD

**Issue by RussKie** [DotNetAnalyzers/StyleCopAnalyzers#3293] opened 2021-01-18 04:54 UTC
Originally discovered in https://github.com/gitextensions/gitextensions/pull/8737

C# 9 has introduced new pattern matching constructs (e.g. `bool IsLetter(char c) => c is (>= 'a' and <= 'z') or (>= 'A' and <= 'Z');`) and more often than not parenthesis are required to clearly state the intent.
Whilst the parenthesis in this sample are not strictly speaking necessary, they greatly enhance readability and guard against accidental order of precedence bugs.
E.g. in the following example parens are must:
```diff
-            bool drawSplitLine = State == PushButtonState.Hot || State == PushButtonState.Pressed || !Application.RenderWithVisualStyles;
+            bool drawSplitLine = State is PushButtonState.Hot or PushButtonState.Pressed || !Application.RenderWithVisualStyles;
```

I couldn't find a doc that described order of precedence for these operators. The best I found was ["C# operators and expressions" doc](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/).

However if a project employs [SA1008](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1008.md?rgh-link-date=2021-01-18T02%3A44%3A17Z), it becomes impossible to write this:
```cs
bool drawSplitLine = State is (PushButtonState.Hot or PushButtonState.Pressed) || !Application.RenderWithVisualStyles;
```
...and one would have to write this instead:
```cs
bool drawSplitLine = State is(PushButtonState.Hot or PushButtonState.Pressed) || !Application.RenderWithVisualStyles;
```
...which doesn't look consistent with the rest of the codebase.

**Comment by sharwell** [comment] 2021-01-18 07:07
Duplicate of #3230

**Closed by sharwell** 2021-01-18 07:07 UTC
