### ISSUE TITLE
// <auto-generated/> tag ignored

### ISSUE THREAD

**Issue by Anakael** [DotNetAnalyzers/StyleCopAnalyzers#3517] opened 2022-06-01 16:34 UTC
Repro steps:
1) Add StyleCop.Analyzers (version 1.1.118)
2) Create database migration through ef Tool
3) Put `// <auto-generated/>` tag at the top of generated file with migration

Expected behavior: Warnings in generated file are ignored

Actual behavior: Warnings in generated file aren't ignored and with `TreatWarningsAsErrors` options build fails

**Comment by sharwell** [comment] 2022-06-01 21:11
Can you include the version of the compiler as well? You can get this by adding `#error version` to a file, and then running a build to see the actual version of the compiler used in the build.

Also, can you include an example of the specific diagnostic ID which is reported in the file which was marked with `<auto-generated/>`?

**Comment by sharwell** [comment] 2022-06-02 16:33
CS1591 is reported by the compiler, not StyleCop Analyzers, so we don't have any control over where/how it is reported. I typically recommend disabling this warning as described here:
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA0001.md#how-to-fix-violations

**Comment by sharwell** [comment] 2022-06-02 16:34
Duplicate of dotnet/roslyn#41171

**Closed by sharwell** 2022-06-02 16:34 UTC
Labels: external
