### ISSUE TITLE
False positive for SA1122 inside switch expression 

### ISSUE THREAD

**Issue by sungam3r** [DotNetAnalyzers/StyleCopAnalyzers#3124] opened 2020-03-13 10:11 UTC
```c#
 internal class Test
    {
        internal static string Echo(string source)
            => source switch
            {
                "" => "empty", // SA1122  Use string.Empty for empty strings
                _ => source
            };
    }
```
After applying "Replace with string.Empty" quick fix:

```c#
 internal class Test
    {
        internal static string Echo(string source)
            => source switch
            {
                string.Empty => "empty", // CS0150  A constant value is expected
                _ => source
            };
    }
```

**Comment by sharwell** [comment] 2020-03-28 07:54
Duplicate of #3028

**Closed by sharwell** 2020-03-28 07:54 UTC
