### ISSUE TITLE
SA1025 doesn't detect multiple spaces before out parameter in a method call

### ISSUE THREAD

**Issue by mdonatas** [DotNetAnalyzers/StyleCopAnalyzers#2787] opened 2018-09-13 10:57 UTC
<pre>Enum.TryParse(imageSizeString,      out ImageSizeEnum imageSize);</pre>
[SA1025](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1025.md) ignores multiple spaces before `out` keyword

**Comment by vweijsters** [comment] 2018-09-29 13:36
Sorry for the `needs discussion` label. This is not a bug for SA1025. This should trigger SA1001.

**Comment by vweijsters** [comment] 2018-09-29 13:45
@sharwell is this really a bug?

The documentation for SA1025 states that spaces following a comma are excluded and the current implementation is such that any multiple spaces between parameters are ignored.

This somehow does not feel right to me, and I'll be happy to change that behaviour, but lets discuss first.

**Comment by sharwell** [comment] 2018-10-01 11:47
I can think of a bunch of cases where users could be depending on the current behavior. Most are related to inline tabular data (e.g. part of collection initializers), but other cases could include range from constructor arguments in tabular data to attribute arguments for things like `InlineData`. This seems sufficient to close this as By Design, although we could still entertain more specific proposals for behavior change and/or options if someone finds one with a low rate of false positives.

**Closed by sharwell** 2018-10-01 11:47 UTC
Labels: bug, needs discussion
