### ISSUE TITLE
Using file-scoped namespace, rules SA1402 (File may only contain a single type) and SA1649 (File name should match first type name) do not trigger

### ISSUE THREAD

**Issue by Hottemax** [DotNetAnalyzers/StyleCopAnalyzers#3477] opened 2022-04-04 07:04 UTC
- When switching to block-scoped namespace, the warning resurfaces.

**Comment by sharwell** [comment] 2022-04-04 15:30
Duplicate of #3435

**Closed by sharwell** 2022-04-04 15:30 UTC
Labels: duplicate
