### ISSUE TITLE
SA1000 rule does not take into consideration the new usage of "new" operator introduced in C# 9.0

### ISSUE THREAD

**Issue by twojnarowski** [DotNetAnalyzers/StyleCopAnalyzers#3554] opened 2022-08-19 12:49 UTC
Documentation for rule [SA1000](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1000.md) states that:

> The new and stackalloc keywords should always be followed by a space, except in the following cases:
> - The new or stackalloc keyword is used to create a new implicitly-typed array. In this case there should be no space between the keyword and the opening array bracket.
> - The new keyword is part of a generic type constraint. In this case there should be no space between the new keyword and the opening parenthesis.

But looking at the [Microsoft Docs](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/new-operator#constructor-invocation) for the new keyword, I can see the following statement:

> Beginning with C# 9.0, constructor invocation expressions are target-typed. That is, if a target type of an expression is known, you can omit a type name, as the following example shows:
> `List<int> xs = new();`

And the default Code Formatting tool in Visual Studio 2022 formats this kind of code so that there is no space after `new`. But StyleCop raises a warning:

> SA1000 The keyword 'new' should be followed by a space.

So fixing this warning and adding space so that `new();` becomes `new ();` is incorrect and will be reverted back to `new();` every time the document is formatted. Rule SA1000 should be improved to handle this new usage of the new operator.

**Comment by bjornhellander** [comment] 2022-08-20 05:35
I agree that the documentation is incomplete, but do not see any SA1000 for this when using the latest version of his package. Are you using the latest beta version?

**Comment by twojnarowski** [comment] 2022-08-25 12:39
I am using the 1.1.118 version.

**Comment by bjornhellander** [comment] 2022-08-25 19:19
1.1.118 is from 2019 and is therefore too old for c# 9. The recommendation is to use the beta packages.

**Comment by twojnarowski** [comment] 2022-08-25 19:32
Ok, I will try the new beta version.

**Comment by sharwell** [comment] 2022-08-29 13:24
Duplicate of #3214

**Closed by sharwell** 2022-08-29 13:24 UTC
