### ISSUE TITLE
StyleCopViolations.xml output file not generated

### ISSUE THREAD

**Issue by pdm1985** [DotNetAnalyzers/StyleCopAnalyzers#1892] opened 2015-12-03 15:23 UTC
The file "StyleCopViolations.xml" seems not to be generated anymore like in previous stylecop versions. Does it have another name?

**Comment by sharwell** [comment] 2015-12-03 17:21
Duplicate of #1090 / #1178.

**Comment by whut** [comment] 2015-12-03 17:22
I believe it is not needed now, as the StyleCop warnings are reported by the C# compiler as the SA*** warnings. To save build log with warnings use the /filelogger switch to msbuild ([here](https://msdn.microsoft.com/en-us/library/ms171470.aspx#Anchor_1) is the documentation)

**Closed** 2015-12-03 17:22 UTC
Labels: duplicate

**Comment by stgeorge** [comment] 2016-02-10 20:40
Microsoft still generates CodeAnalysisLog.xml for FxCop (which are now analyzers as well) - so I think an XML export file (in the same exact format) is still needed because there are still downstream tools in build processes that expect a StyleCopViolations.xml file...

**Comment by sharwell** [comment] 2016-02-10 22:21
@stgeorge At last I checked, FxCop analysis was planned for a move to analyzers but had not yet moved. I expect that the log file will disappear when the transition is complete.

**Comment by vweijsters** [comment] 2016-02-11 20:22
There is a  [Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers/) package that afaik is a port of FxCop to analyzers. Whether or not it produces an XML file I don't know, but I couldn't find any reference to it [roslyn-analyzers](https://github.com/dotnet/roslyn-analyzers).
