### ISSUE TITLE
SA1009 conflicts with SA1024 for primary constructors with parent classes.

### ISSUE THREAD

**Issue by mrudat** [DotNetAnalyzers/StyleCopAnalyzers#3844] opened 2024-05-19 06:33 UTC
I prefer this option:

```cs
[SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1009:Closing parenthesis should be spaced correctly", Justification = "Conflicts with SA1024")]
public class Class(string stringOption) : ParentClass(stringOptions)

[SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1009:Closing parenthesis should be spaced correctly", Justification = "Conflicts with SA1024")]
public class Class2(string stringOption) : IParentInterface
```

```cs
[SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1024:Colons Should Be Spaced Correctly", Justification = "Conflicts with SA1009")]
public class Class(string stringOption): ParentClass(stringOptions)

[SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1024:Colons Should Be Spaced Correctly", Justification = "Conflicts with SA1009")]
public class Class2(string stringOption): IParentInterface
```

**Comment by mrudat** [comment] 2024-05-19 07:43
Alternatively, when there is a parent constructor, given [SA1128](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1128.md), should that instead be:

```cs
public class Class(string stringOptions)
    : ParentClass(stringOptions)
```

**Comment by sharwell** [comment] 2024-05-21 13:21
Duplicate of #3248

**Closed by sharwell** 2024-05-21 13:21 UTC
