### ISSUE TITLE
ExcludeFromStyleCop should accept True as well as true

### ISSUE THREAD

**Issue by rkeithhill** [DotNetAnalyzers/StyleCopAnalyzers#1727] opened 2015-11-04 18:47 UTC
I was wondering why StyleCop.Analyzers wasn't skipping a file and it was because I used the value `True` which is prevalent in CSPROJ file.  It seems to me that both `True` and `true` should be accepted.

**Comment by sharwell** [comment] 2015-11-04 18:51
Currently StyleCop Analyzers doesn't support ExcludeFromStyleCop at all. This is a duplicate of #726.

**Closed** 2015-11-04 18:52 UTC
Labels: duplicate

**Comment by rkeithhill** [comment] 2015-11-04 19:08
Yeah, I just noticed that.  Thought it was working but no.  :-(
