### ISSUE TITLE
Publish 1.0.1 package in nuget?

### ISSUE THREAD

**Issue by xumix** [DotNetAnalyzers/StyleCopAnalyzers#2342] opened 2017-04-12 10:24 UTC
please

**Comment by stffabi** [comment] 2017-04-13 06:45
Yes, this is currently a serious problem.

**Comment by mikes-gh** [comment] 2017-04-18 13:07
I don't believe 1.0.1 will ever be released as there was a problem with it.
What did you need 1.0.1 for?
I am awaiting netcore/xplat-msbuild support as currently cant use the analyser in vscode.

**Comment by xumix** [comment] 2017-04-18 13:09
@mikes-gh well, there were some fixes that I wanted and I'd like a fresh build to be available from official store

**Comment by mikes-gh** [comment] 2017-04-18 13:11
I think the big blocker is netstandard support which doesn't appear to be straight forward.  Any news @sharwell

**Comment by mikes-gh** [comment] 2017-04-18 13:16
@xumix If you were waiting for fixes I don't believe there was anything in 1.0.1 that wasn't in 1.0.0 
1.0.1 was an attempt at solving a problem with JSON.net on netstandard.

**Comment by xumix** [comment] 2017-04-18 13:36
@mikes-gh oops, i'm sorry, I've waited for 1.1 fixes

**Comment by sharwell** [comment] 2017-04-18 15:58
@xumix I'm going to treat this like the title says currently. If you meant a different number, feel free to open a different issue.

The 1.0.1 release was intended to fix some compatibility issues with .NET Core users. In practice, it did not behave as we intended so I unlisted the package in NuGet. I'm still working with others on the Roslyn team to come up with a good story for analyzers in cross-platform development scenarios. I don't have news yet but hopefully soon; it's causing a big pain point and not just for user of this project.

**Closed by sharwell** 2017-04-18 15:58 UTC
