### ISSUE TITLE
SA1203 Quick Action not shown

### ISSUE THREAD

**Issue by kindermannhubert** [DotNetAnalyzers/StyleCopAnalyzers#2111] opened 2016-03-30 07:32 UTC
While using SA1203 it is successfuly detected:
![sa1203_a](https://cloud.githubusercontent.com/assets/11704036/14134858/0a0b96a8-f65a-11e5-8eef-ba7f722ac85b.png)
but after presing "Ctrl + ." I don't see fix for SA1203:
![sa1203_b](https://cloud.githubusercontent.com/assets/11704036/14134892/497683f2-f65a-11e5-97ed-4e5f0e7b4829.png)

**Comment by sharwell** [comment] 2016-04-11 22:34
@kindermannhubert What version are you using? We disabled this code fix for the 1.0 release due to a number of reliability issues.

Marking as a duplicate of #1869.

**Closed by sharwell** 2016-04-11 22:34 UTC
Labels: bug, up for grabs

**Comment by kindermannhubert** [comment] 2016-04-12 07:57
@sharwell I'm using last version from master branch.

**Comment by sharwell** [comment] 2016-04-12 11:36
@kindermannhubert Thanks. Since #1869 has not yet been resolved, it means this code fix is still disabled in the master branch.
