### ISSUE TITLE
New rule proposal: XMLDoc documentation of a method needs to list all not-caught exceptions thrown in that exact method

### ISSUE THREAD

**Issue by ndsvw** [DotNetAnalyzers/StyleCopAnalyzers#3475] opened 2022-03-28 09:41 UTC
We are interested in knowing whether it's possible to create a new rule that makes sure that every uncaught exception thrown in a method has to be documented in the XML documentation of the method?

---

Noncompliant:

```
public void X(){
    throw new Exception();
}
```

Compliant:

```
/// <exception cref="Exception">Some text</exception>
public void X(){
    throw new Exception();
}
```

Compliant:

```
public void X(){
    try{
        throw new Exception();
    } catch(Exception e){

    }
}
```

---

Compliant (X does not need to document an exception that is thrown in a called method):

```
public void X(){
    Y();
}

/// <exception cref="Exception">Some text</exception>
public void Y(){
    throw new Exception();
}
```

---

Is it hypothetically possible to implement this?

One possible problem could be the `catch (Exception e) when (expr)` syntax which makes is potentially impossible to find out during compile time whether an exception will always be caught or not.

**Comment by sharwell** [comment] 2022-03-29 15:11
I'm hesitant to implement this rule based on the outcome of Redgate Exception Hunter. This commercial product attempted to solve this problem for code, but it was so problematic that the company discontinued the product altogether.

**Comment by sharwell** [comment] 2022-03-29 15:12
Duplicate of #1950

**Closed by sharwell** 2022-03-29 15:12 UTC
Labels: duplicate
