### ISSUE TITLE
Analyzers removed from csproj files during nuget upgrade to 1.0.2

### ISSUE THREAD

**Issue by bussemac** [DotNetAnalyzers/StyleCopAnalyzers#2542] opened 2017-10-13 19:10 UTC
Given a csproj running 1.0.0 Analyzers, that looks like this...

```
<ItemGroup>
    <AdditionalFiles Include="..\..\stylecop.json">
      <Link>stylecop.json</Link>
    </AdditionalFiles>
    <None Include="app.config" />
    <None Include="packages.config" />
  </ItemGroup>
  <ItemGroup>
    <Analyzer Include="..\..\packages\StyleCop.Analyzers.1.0.0\analyzers\dotnet\cs\Newtonsoft.Json.dll" />
    <Analyzer Include="..\..\packages\StyleCop.Analyzers.1.0.0\analyzers\dotnet\cs\StyleCop.Analyzers.CodeFixes.dll" />
    <Analyzer Include="..\..\packages\StyleCop.Analyzers.1.0.0\analyzers\dotnet\cs\StyleCop.Analyzers.dll" />
  </ItemGroup>
```

StyleCop is working correctly, enforced on build. I then open the Package Manager Console and run `Update-Package StyleCop.Analyzers` to upgrade to 1.0.2 across the board. After the upgrade, the `ItemGroup` with `Analyzer` tags is missing, and StyleCop does not enforce anything nor suggest anything for intellisense. The `<PropertyGroup>` blocks do have `<CodeAnalysisRuleset>` set to a valid ruleset file.

If I explicitly run `Update-Package StyleCop.Analyzers -reinstall -ProjectName MyProject.Foo` then the analyzers come back. Sometimes it takes two tries, and sometimes running it twice removes the analyzers again, and sometimes I wind up with a 1.0.0 Newtonsoft.Json.dll and 1.0.2 for the other two, or no Newtonsoft at all.

**Comment by sharwell** [comment] 2017-10-17 04:23
Most likely this is a duplicate of NuGet/Home#6035.

**Comment by vweijsters** [comment] 2018-07-11 12:47
The mentioned NuGet issue is fixed and released.

**Closed by vweijsters** 2018-07-11 12:47 UTC
