### ISSUE TITLE
Usage of _ in methods arguments raises SA1313

### ISSUE THREAD

**Issue by Onzi12** [DotNetAnalyzers/StyleCopAnalyzers#2599] opened 2018-01-22 08:59 UTC
Usage of _ in method arguments raises [SA1313](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1313.md).

Example:
```C#
public override void Foo( int arg, int _ )
{
...
}
```

Can you please make an exception to [SA1313](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1313.md), to support '_' in method arguments?

**Comment by brinko99** [comment] 2018-01-22 21:32
I agree. As is, an exception is made for lambda expressions...

In fact, I would request that any number of ignored parameters be supported in this way. This supports the cases where multiple parameters are to be ignored.

e.g. `MyProperty.PropertyChanged += (_, __) => ...`

**Comment by sharwell** [comment] 2018-01-25 15:29
I'm not sure I agree with this one. Plus, it's going to conflict with #1949.

@brinko99 Your case is a duplicate of #1606.

**Comment by Onzi12** [comment] 2018-01-25 16:13
Why are you not sure you agree? 
The purpose of the _ is to acknowledge the arg is not in use.
Without this enhancement, users can use this feature **ONLY** in lambda handlers.

About the conflict with  [#1949](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/1949) I agree. Implementing this should include an exception to  [#1949](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/1949).

**Comment by sharwell** [comment] 2020-11-17 17:41
Closing this one as **won't fix**. The recommended solution for method signatures when a parameter is intentionally not used is:

1. Give the parameter a meaningful name. This should match the original definition when applicable (see #1949).
2. Assign the parameter to a discard at the start of the method to clearly indicate to the reader that the parameter is intentionally unused.

For example:

```csharp
public void Method(T value)
{
  _ = value;
}
```

**Closed by sharwell** 2020-11-17 17:41 UTC
Labels: enhancement, needs discussion

**Comment by tutike2000** [comment] 2022-02-06 12:53
Why close this as won't fix if so many people want it fixed?

**Comment by sharwell** [comment] 2022-02-07 03:51
@tutike2000 There is no requirement that a project enable SA1313 or use it without modification. Options for resolving this externally include:

* SA1313 can be disabled, and a new rule implemented separately that is used instead. The new rule can be based on SA1313 and even start with its code under the MIT license.
* SA1313 can be left enabled, and a `DiagnosticSuppressor` implemented separately that prevents SA1313 from reporting in the location described by this issue. I faced a [similar issue](https://github.com/microsoft/vs-threading/issues/670) with [VSTHRD200](https://github.com/microsoft/vs-threading/blob/26b09cb244e2b0fdd0cdeca5c9d67a8dad390990/doc/analyzers/VSTHRD200.md) and resolved it by writing [`RelaxTestNamingSuppressor`](https://github.com/dotnet/roslyn-analyzers/blob/60eb13c44c366205e5a4dec195404477009c41de/src/Roslyn.Diagnostics.Analyzers/Core/RelaxTestNamingSuppressor.cs).

**Comment by palenshus** [comment] 2022-11-15 19:21
Currently `IDE0060` suggests that we do in fact rename unused parameters to `_`:

`IDE0060	Remove unused parameter 'sender' if it is not part of a shipped public
Avoid unused parameters in your code. If the parameter cannot be removed, then change its name so it starts with an underscore and is optionally followed by an integer, such as '_', '_1', '_2', etc. These are treated as special discard symbol names.`

However, if we follow that advice, given by the IDE, then we run into this issue. That doesn't seem like a good thing to Won't Fix

**Comment by Lowlet** [comment] 2024-10-26 04:07
This should be fixed
