### ISSUE TITLE
SA1200 Stops when adding two class files

### ISSUE THREAD

**Issue by shaggygi** [DotNetAnalyzers/StyleCopAnalyzers#1940] opened 2015-12-10 02:04 UTC
Seeing some odd things with SA1200 (moving usings within namespace).  I can add a class file to a project and will see the green squiggles and can CTRL+. to move into namespace.  If I add a 2nd class file, the rule stops.  If I delete or exclude the 2nd class file, the squiggles come back.

This seemed to work before as I've tried with different versions as the team released them.  However, it appears to have recently stopped.  I'm sure it is something I've done in my IDE, but don't know if anyone else has seen this problem.

Thoughts?

UPDATE:  I didn't see #1939 before creating this issue.  It seems like my issue started after updating Update 1, as well.

**Comment by sharwell** [comment] 2015-12-10 17:30
I haven't figured out *why* this is happening yet, but I'm going to treat this as a duplicate of #1939 (at least for now).

**Closed by sharwell** 2015-12-10 17:30 UTC
