### ISSUE TITLE
SA1206 suggests a non-idiomatic placement of the required modifier.

### ISSUE THREAD

**Issue by mrudat** [DotNetAnalyzers/StyleCopAnalyzers#3846] opened 2024-05-19 08:42 UTC
As far as I can tell, the preferred way to specify [required](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/required) is:

```
public required string WeNeedThisString { get; init; }
```

And not, as SA1206 suggests:

```
required public string WeNeedThisString { get; init; }
```

**Comment by bjornhellander** [comment] 2024-05-19 12:13
Which version are you using?

**Comment by bjornhellander** [comment] 2024-05-19 14:13
I am unable to reproduct this with the latest beta

**Comment by mrudat** [comment] 2024-05-19 14:30
The latest release available via NuGet.

**Comment by sharwell** [comment] 2024-05-21 13:16
Duplicate of #3527

**Closed by sharwell** 2024-05-21 13:16 UTC

**Comment by bjornhellander** [comment] 2024-05-24 07:27
@mrudat A clarification: We are assuming that you are using version 1.1.118, which is from 2019 and have big problems with modern c# features. Since then there has been only beta release, which is of course easy to miss when installing packages. If you want to have StyleCop.Analyzers installed and use modern c# features, you will have bad experience if you are not using the beta versions.

**Comment by 51dario51** [comment] 2024-06-09 09:56
Is any official release of the current latest beta planned?
Of course we could simply update the package to the latest beta, but how safe is this beta?
