### ISSUE TITLE
Rule proposal: No blank line between XML documentation and attribute

### ISSUE THREAD

**Issue by vweijsters** [DotNetAnalyzers/StyleCopAnalyzers#740] opened 2015-04-27 11:17 UTC
I got triggered after reading #737. Blank lines after the attribute are covered by #738. 

If XML documentation is followed by an attribute, there should be no blank line between them.
Rationale: Packing the xml documentation, attributes and definitions close together improves readability by reducing the amount of vertical room needed. The three parts are clearly distinguishable because of their unique syntax.

**Comment by Przemyslaw-W** [comment] 2015-04-27 11:36
Isn't this covered by SA1506?

2015-04-27 13:17 GMT+02:00 Vincent Weijsters <notifications@github.com>:

**Comment by sharwell** [comment] 2015-04-27 13:24
Duplicate of #107.

**Closed by sharwell** 2015-04-27 13:24 UTC
