### ISSUE TITLE
SA1010 interferes with IDE0055 when = is followed by an array initialization

### ISSUE THREAD

**Issue by Psichorex** [DotNetAnalyzers/StyleCopAnalyzers#3794] opened 2024-02-01 19:05 UTC
SA1010 interferes with IDE0055 provided the following example:

`var myArray = ["string1","string2"]` because this is SA1010 but the solution `var myArray =["string1","string2"]` is wierd and also produces IDE0055

IDE0055 -> https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0055
SA1010 -> https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1010.md

**Comment by bjornhellander** [comment] 2024-02-04 06:42
Unable to reproduce this. Seems like a duplicate of #3687. If you upgrade to 1.2.0-beta.556, this should go away.

**Comment by Piedone** [comment] 2024-02-04 19:10
That looks like it, because I believe Roland tried this with v1.2.0-beta.435, but @Psichorex please confirm.

**Comment by sharwell** [comment] 2024-02-05 13:31
Duplicate of #3687

**Closed by sharwell** 2024-02-05 13:31 UTC

**Comment by Psichorex** [comment] 2024-02-05 13:49
It is indeed solved by upgrading to `v1.2.0-beta.556`
