### ISSUE TITLE
SA1413 falsely generated

### ISSUE THREAD

**Issue by powerdude** [DotNetAnalyzers/StyleCopAnalyzers#2884] opened 2019-02-14 00:55 UTC
The following code:
```
            var model = await this.mediator.Send(
                            new GetSessionDetailQuery
                            {
                                Id = id
                            });

```
causes a SA1413 warning when it really shouldn't.  The warning should not happen for the last line in a multi-line initializer

**Comment by sharwell** [comment] 2019-02-14 03:20
Yes, this is the main goal of SA1413. Sometimes SA1413 is confused with a readability rule when people see in the first time, but it is actually a maintainability rule. Please see the documentation in [SA1413.md](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1413.md) for more information.

**Comment by sharwell** [comment] 2019-02-14 03:21
Duplicate of #2416

**Closed by sharwell** 2019-02-14 03:20 UTC

**Comment by powerdude** [comment] 2019-02-14 03:33
ahh, i see.  I like it.  I used the github search to try and find SA1413, but it didn't find the doc.  sorry for the dupe and thanks.

**Comment by sharwell** [comment] 2019-02-14 03:41
No problem 👍
