### ISSUE TITLE
SA 1122 Is Triggered When Using Case Statement

### ISSUE THREAD

**Issue by lumberjack4** [DotNetAnalyzers/StyleCopAnalyzers#1319] opened 2015-08-29 02:08 UTC
```
switch(myString)
{
    case "":
    break;
    case "A":
    break;
    case "B":
    break;
}
```

case "": triggers SA 1122.  string.Empty cannot be used in this scenario because the string must be a compile time constant.  This was seen using beta 8.

**Comment by sharwell** [comment] 2015-08-29 02:39
Duplicate of #1281. It's been fixed for Beta 9 (which will be coming soon).

**Closed by sharwell** 2015-08-29 02:39 UTC
