### ISSUE TITLE
C# 9 record definition using constructor raises SA1313

### ISSUE THREAD

**Issue by manfred-brands** [DotNetAnalyzers/StyleCopAnalyzers#3232] opened 2020-11-11 06:46 UTC
A `record` type can be defined with a constructor where the parameter names become the Properties, such as in:

```
internal record Person(string FirstName, string LastName);
```

StyleCop raises SA1313: _Parameter 'FirstName' should begin with a lower-case letter_. Doing so raises IDE1006.
These are not just parameter name but also Property names.

Can StyleCop detect the difference?

**Comment by sharwell** [comment] 2020-11-11 15:26
Duplicate of #3181

**Closed by sharwell** 2020-11-11 15:26 UTC
