### ISSUE TITLE
New rule proposal: SX1101 DoNotPrefixLocalMembersWithThis

### ISSUE THREAD

**Issue by vweijsters** [DotNetAnalyzers/StyleCopAnalyzers#1601] opened 2015-10-06 18:48 UTC
**Category:** Readability
**Title:** Do not prefix local members with this
**Description:** A violation of this rule occurs whenever the code contains a call to an instance member of the local class or a base class which is prefixed with `this.`.
**Rationale:** This rule as an alternative rule for SA1101 (PrefixLocalCallsWithThis). This rule is most likely to be used in conjunction with SX1309 (FieldNamesMustBeginWithUnderscore) (and/or SX1309S (StaticFieldNamesMustBeginWithUnderscore)). A typical usage scenario when using members starting with underscores is to not use the `this.` prefix. I think we should offer our users the possibility to enforce this. This rule will be disabled by default.

**Comment by Maxwe11** [comment] 2015-10-06 18:53
:+1:

**Comment by sharwell** [comment] 2015-10-06 19:13
I believe this rule is a duplicate of IDE0003. If so, equivalent behavior could be provided simply by setting IDE0003 to a higher-than-default severity (default is Hidden, but could be Warning or Error).

**Comment by vweijsters** [comment] 2015-10-14 08:30
I would still prefer to add the rule, even though IDE0003 is (almost) identical.
As indicated, IDE0003 has issues and from an end user perspective it would make more sense to have all related code styling rules in a single analyzer, as that would keep rule set maintenance a lot easier.

**Comment by sharwell** [comment] 2015-10-14 17:50
:+1:

**Comment by vweijsters** [comment] 2015-10-14 19:02
Grabbing this

**Closed** 2015-10-23 22:20 UTC
Labels: new rule, pull request, readability
