### ISSUE TITLE
SA1119 broken for " x is null" expressions

### ISSUE THREAD

**Issue by smaillet** [DotNetAnalyzers/StyleCopAnalyzers#2550] opened 2017-10-29 04:40 UTC
SA119 triggers, given the expression:
``` C#
!(other is null) && x == other.x
```

However, the parenthesis are required for that expression and cannot be removed.

**Comment by sharwell** [comment] 2017-10-29 12:16
:memo: This is probably a duplicate of #2372, in which case it's already fixed as part of the 1.1.0 Beta 4 release.

**Closed** 2017-10-31 13:38 UTC
Labels: duplicate
