### ISSUE TITLE
The `<inheritdoc />` tag should be exempt from the SA1625 rule.

### ISSUE THREAD

**Issue by PatrickBig** [DotNetAnalyzers/StyleCopAnalyzers#3257] opened 2020-12-01 15:33 UTC
The `<inheritdoc />` tag should be exempt from the SA1625 rule.

 

In situations with inheritance it can be useful to pull documentation from the base class instead of re-writing it.

 

Eg:

 

```csharp

public abstract class MyClass

{

    /// <summary>

    /// This will write a message to the user.

    /// </summary>

    /// <param name="message">The message that will be written.</param>

    public abstract void WriteMessage(string message);

}

 

 

public class AnotherClass : MyClass

{

    /// <summary>

    /// <inheritdoc />

    /// </summary>

    /// <param name="message"><inheritdoc /></param>

    public override void DoSomething(string message)

    {

        Console.WriteLine(message);

    }

}

```

**Comment by sharwell** [comment] 2020-12-01 18:32
Duplicate of #3108

**Closed by sharwell** 2020-12-01 18:32 UTC
Labels: bug, up for grabs
