### ISSUE TITLE
The fix for SA1312 can violate SA1300

### ISSUE THREAD

**Issue by Tinister** [DotNetAnalyzers/StyleCopAnalyzers#1425] opened 2015-09-09 01:41 UTC
See this example:

    public class ClassName
    {
        protected event EventHandler EventName;
    }

This gets flagged as an SA1312 violation, and you are offered to make `EventName` camel case.

But once it's camel case, `eventName` is flagged as an SA1300 violation and you get offered to make it pascal case.

FYI, "old" Style Cop prefers this to be pascal case.

**Comment by sharwell** [comment] 2015-09-09 05:12
Duplicate of #1340.

**Closed by sharwell** 2015-09-09 05:12 UTC
