### ISSUE TITLE
ArgumentOutOfRangeException in SA1508ClosingCurlyBracketsMustNotBePrecededByBlankLine

### ISSUE THREAD

**Issue by appel1** [DotNetAnalyzers/StyleCopAnalyzers#1632] opened 2015-10-15 08:06 UTC
Every now and then while editing code I get an error in the SA1508ClosingCurlyBracketsMustNotBePrecededByBlank rule. Haven't been able to figure out how to reproduce it yet. 

```
Severity	Code	Description	Project	File	Line	Detail Description
Message	AD0001	The User Diagnostic Analyzer 'StyleCop.Analyzers.LayoutRules.SA1508ClosingCurlyBracketsMustNotBePrecededByBlankLine' threw an exception of type 'System.ArgumentOutOfRangeException' with message 'Specified argument was out of the range of valid values.
Parameter name: index'.	<assemblyname>		1	Analyzer 'StyleCop.Analyzers.LayoutRules.SA1508ClosingCurlyBracketsMustNotBePrecededByBlankLine' threw the following exception:
'System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: index
   at Microsoft.CodeAnalysis.SyntaxTriviaList.get_Item(Int32 index)
   at StyleCop.Analyzers.Helpers.TriviaHelper.DualTriviaListHelper.get_Item(Int32 index)
   at StyleCop.Analyzers.LayoutRules.SA1508ClosingCurlyBracketsMustNotBePrecededByBlankLine.AnalyzeCloseBrace(SyntaxNodeAnalysisContext context, SyntaxToken closeBraceToken)
   at StyleCop.Analyzers.LayoutRules.SA1508ClosingCurlyBracketsMustNotBePrecededByBlankLine.HandleTypeDeclaration(SyntaxNodeAnalysisContext context)
   at StyleCop.Analyzers.AnalyzerExtensions.<>c__DisplayClass2_0`1.<RegisterSyntaxNodeActionHonorExclusions>b__0(SyntaxNodeAnalysisContext c)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass35_0`1.<ExecuteSyntaxNodeAction>b__1()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze)'.
```

**Comment by sharwell** [comment] 2015-10-15 11:25
Duplicate of #1534 :smile:

**Closed by sharwell** 2015-10-15 11:25 UTC
