### ISSUE TITLE
Missing stylecop.json file but in project causes nullrefs

### ISSUE THREAD

**Issue by hvanbakel** [DotNetAnalyzers/StyleCopAnalyzers#2188] opened 2016-08-10 14:56 UTC
If your project file says that it has a stylecop.json file but the file is not phyically present on disk (e.g. the file was not added to source control for some reason) a number of rules start throwing null ref exceptions.

**Comment by sharwell** [comment] 2016-08-10 16:31
Duplicate of #2073 :smile:

**Closed by sharwell** 2016-08-10 16:31 UTC
