### ISSUE TITLE
SA1649 Does not work correctly in Enum type files with other types following

### ISSUE THREAD

**Issue by mikernet** [DotNetAnalyzers/StyleCopAnalyzers#3406] opened 2021-11-23 00:58 UTC
File is named `DeleteFailureMode.cs`:

```cs
    [Flags]
    public enum DeleteFailureMode
    {
    }

    // Requires SA1649 to be disabled:
    #pragma warning disable SA1649 // File name should match first type name

    internal static class DeleteFailureModeExtensions
    {
    }
````

**Comment by sharwell** [comment] 2021-11-23 19:19
Duplicate of #2223

**Closed by sharwell** 2021-11-23 19:19 UTC
