### ISSUE TITLE
SA1000 conflict with new operator C# 9.0

### ISSUE THREAD

**Issue by fsomm** [DotNetAnalyzers/StyleCopAnalyzers#3355] opened 2021-06-18 09:56 UTC
There is a conflict using the new operator in C# 9.0 with the rule SA1000.
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/new-operator#constructor-invocation

e.g.

![image](https://user-images.githubusercontent.com/86104744/122543220-d293ba00-d02b-11eb-9090-9f77c2701322.png)

Unfortunately this rule is not only related to the new operator but to more keywords.
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1000.md

Deactivating this also affects other keywords.

**Comment by sharwell** [comment] 2021-06-18 14:33
Duplicate of #3214

**Closed by sharwell** 2021-06-18 14:33 UTC
