### ISSUE TITLE
SA1500, SA1502, SA1508 NullReferenceException with C# 9 record classes

### ISSUE THREAD

**Issue by starkcolin** [DotNetAnalyzers/StyleCopAnalyzers#3286] opened 2020-12-29 15:36 UTC
Several analyzer errors are being caused by the use of the new C# 9 record classes.  In another file where the class also has a body, there is no issue.  Only the simple definition seems to trigger the issues, whether single-line or multi-line.  Sample class and all the exceptions visible in the VS error window are included below.  Namespaces have been changed so hopefully that doesn't throw off any references using character number.

Version: 1.2.0-beta.312
This running on .NET Core 3.1, not .NET 5.0, in case that makes a difference.

```
// <copyright file="EmailTemplateInfo.cs" company="My Company">
// Copyright (c) My Company. All rights reserved.
// </copyright>

namespace MyCompany.MyApp.WebApi.Infrastructure
{
    using System.Collections.Generic;

    using MyCompany.MyApp.DataModel.V1.Model;

    public record EmailTemplateInfo(
        string JobName,
        string JobId,
        string JobRunId,
        string Start,
        string End,
        string Duration,
        string ManageUri,
        string JobRunText,
        List<EmailModelInfo> ModelInfos);

    public record EmailModelInfo(string Id, string Name, JobRunStatusType StatusType, string ErrorMessage);
}
```

```
Analyzer 'StyleCop.Analyzers.LayoutRules.SA1500BracesForMultiLineStatementsMustNotShareLine' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
Exception occurred with following context:
Compilation: MyCompany.App.WebApi
SyntaxTree: C:\Users\stark\source\repos\MyCompany.App\src\MyCompany.App.WebApi\Infrastructure\EmailTemplateInfo.cs
SyntaxNode: public record EmailModelInfo(string ... [RecordDeclarationSyntax]@[576..679) (21,4)-(21,107)

System.NullReferenceException: Object reference not set to an instance of an object.
   at StyleCop.Analyzers.Helpers.LocationHelpers.GetLineSpan(SyntaxToken token)
   at StyleCop.Analyzers.Helpers.LocationHelpers.GetLine(SyntaxToken token)
   at StyleCop.Analyzers.LayoutRules.SA1500BracesForMultiLineStatementsMustNotShareLine.CheckBraces(SyntaxNodeAnalysisContext context, SyntaxToken openBraceToken, SyntaxToken closeBraceToken)
   at StyleCop.Analyzers.LayoutRules.SA1500BracesForMultiLineStatementsMustNotShareLine.HandleBaseTypeDeclaration(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__62`1.<ExecuteSyntaxNodeAction>b__62_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

Analyzer 'StyleCop.Analyzers.LayoutRules.SA1500BracesForMultiLineStatementsMustNotShareLine' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
Exception occurred with following context:
Compilation: MyCompany.App.WebApi
SyntaxTree: C:\Users\stark\source\repos\MyCompany.App\src\MyCompany.App.WebApi\Infrastructure\EmailTemplateInfo.cs
SyntaxNode: public record EmailTemplateInfo ... [RecordDeclarationSyntax]@[294..568) (10,4)-(19,41)

System.NullReferenceException: Object reference not set to an instance of an object.
   at StyleCop.Analyzers.Helpers.LocationHelpers.GetLineSpan(SyntaxToken token)
   at StyleCop.Analyzers.Helpers.LocationHelpers.GetLine(SyntaxToken token)
   at StyleCop.Analyzers.LayoutRules.SA1500BracesForMultiLineStatementsMustNotShareLine.CheckBraces(SyntaxNodeAnalysisContext context, SyntaxToken openBraceToken, SyntaxToken closeBraceToken)
   at StyleCop.Analyzers.LayoutRules.SA1500BracesForMultiLineStatementsMustNotShareLine.HandleBaseTypeDeclaration(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__62`1.<ExecuteSyntaxNodeAction>b__62_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

Analyzer 'StyleCop.Analyzers.LayoutRules.SA1500BracesForMultiLineStatementsMustNotShareLine' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
Exception occurred with following context:
Compilation: MyCompany.App.WebApi
SyntaxTree: C:\Users\stark\source\repos\MyCompany.App\src\MyCompany.App.WebApi\Infrastructure\EmailTemplateInfo.cs
SyntaxNode: public record EmailTemplateInfo ... [RecordDeclarationSyntax]@[294..568) (10,4)-(19,41)

System.NullReferenceException: Object reference not set to an instance of an object.
   at StyleCop.Analyzers.Helpers.LocationHelpers.GetLineSpan(SyntaxToken token)
   at StyleCop.Analyzers.Helpers.LocationHelpers.GetLine(SyntaxToken token)
   at StyleCop.Analyzers.LayoutRules.SA1500BracesForMultiLineStatementsMustNotShareLine.CheckBraces(SyntaxNodeAnalysisContext context, SyntaxToken openBraceToken, SyntaxToken closeBraceToken)
   at StyleCop.Analyzers.LayoutRules.SA1500BracesForMultiLineStatementsMustNotShareLine.HandleBaseTypeDeclaration(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__62`1.<ExecuteSyntaxNodeAction>b__62_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

Analyzer 'StyleCop.Analyzers.LayoutRules.SA1508ClosingBracesMustNotBePrecededByBlankLine' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
Exception occurred with following context:
Compilation: MyCompany.App.WebApi
SyntaxTree: C:\Users\stark\source\repos\MyCompany.App\src\MyCompany.App.WebApi\Infrastructure\EmailTemplateInfo.cs
SyntaxNode: public record EmailTemplateInfo ... [RecordDeclarationSyntax]@[294..568) (10,4)-(19,41)

System.NullReferenceException: Object reference not set to an instance of an object.
   at StyleCop.Analyzers.Helpers.LocationHelpers.GetLineSpan(SyntaxToken token)
   at StyleCop.Analyzers.LayoutRules.SA1508ClosingBracesMustNotBePrecededByBlankLine.AnalyzeCloseBrace(SyntaxNodeAnalysisContext context, SyntaxToken closeBraceToken)
   at StyleCop.Analyzers.LayoutRules.SA1508ClosingBracesMustNotBePrecededByBlankLine.HandleBaseTypeDeclaration(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__62`1.<ExecuteSyntaxNodeAction>b__62_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

Analyzer 'StyleCop.Analyzers.LayoutRules.SA1508ClosingBracesMustNotBePrecededByBlankLine' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
Exception occurred with following context:
Compilation: MyCompany.App.WebApi
SyntaxTree: C:\Users\stark\source\repos\MyCompany.App\src\MyCompany.App.WebApi\Infrastructure\EmailTemplateInfo.cs
SyntaxNode: public record EmailModelInfo(string ... [RecordDeclarationSyntax]@[576..679) (21,4)-(21,107)

System.NullReferenceException: Object reference not set to an instance of an object.
   at StyleCop.Analyzers.Helpers.LocationHelpers.GetLineSpan(SyntaxToken token)
   at StyleCop.Analyzers.LayoutRules.SA1508ClosingBracesMustNotBePrecededByBlankLine.AnalyzeCloseBrace(SyntaxNodeAnalysisContext context, SyntaxToken closeBraceToken)
   at StyleCop.Analyzers.LayoutRules.SA1508ClosingBracesMustNotBePrecededByBlankLine.HandleBaseTypeDeclaration(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__62`1.<ExecuteSyntaxNodeAction>b__62_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

Analyzer 'StyleCop.Analyzers.LayoutRules.SA1508ClosingBracesMustNotBePrecededByBlankLine' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
Exception occurred with following context:
Compilation: MyCompany.App.WebApi
SyntaxTree: C:\Users\stark\source\repos\MyCompany.App\src\MyCompany.App.WebApi\Infrastructure\EmailTemplateInfo.cs
SyntaxNode: public record EmailTemplateInfo ... [RecordDeclarationSyntax]@[294..568) (10,4)-(19,41)

System.NullReferenceException: Object reference not set to an instance of an object.
   at StyleCop.Analyzers.Helpers.LocationHelpers.GetLineSpan(SyntaxToken token)
   at StyleCop.Analyzers.LayoutRules.SA1508ClosingBracesMustNotBePrecededByBlankLine.AnalyzeCloseBrace(SyntaxNodeAnalysisContext context, SyntaxToken closeBraceToken)
   at StyleCop.Analyzers.LayoutRules.SA1508ClosingBracesMustNotBePrecededByBlankLine.HandleBaseTypeDeclaration(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__62`1.<ExecuteSyntaxNodeAction>b__62_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

Analyzer 'StyleCop.Analyzers.LayoutRules.SA1508ClosingBracesMustNotBePrecededByBlankLine' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
Exception occurred with following context:
Compilation: MyCompany.App.WebApi
SyntaxTree: C:\Users\stark\source\repos\MyCompany.App\src\MyCompany.App.WebApi\Infrastructure\EmailTemplateInfo.cs
SyntaxNode: public record EmailModelInfo(string ... [RecordDeclarationSyntax]@[576..679) (21,4)-(21,107)

System.NullReferenceException: Object reference not set to an instance of an object.
   at StyleCop.Analyzers.Helpers.LocationHelpers.GetLineSpan(SyntaxToken token)
   at StyleCop.Analyzers.LayoutRules.SA1508ClosingBracesMustNotBePrecededByBlankLine.AnalyzeCloseBrace(SyntaxNodeAnalysisContext context, SyntaxToken closeBraceToken)
   at StyleCop.Analyzers.LayoutRules.SA1508ClosingBracesMustNotBePrecededByBlankLine.HandleBaseTypeDeclaration(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__62`1.<ExecuteSyntaxNodeAction>b__62_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

Analyzer 'StyleCop.Analyzers.LayoutRules.SA1502ElementMustNotBeOnASingleLine' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
Exception occurred with following context:
Compilation: MyCompany.App.WebApi
SyntaxTree: C:\Users\stark\source\repos\MyCompany.App\src\MyCompany.App.WebApi\Infrastructure\EmailTemplateInfo.cs
SyntaxNode: public record EmailTemplateInfo ... [RecordDeclarationSyntax]@[294..568) (10,4)-(19,41)

System.NullReferenceException: Object reference not set to an instance of an object.
   at StyleCop.Analyzers.Helpers.LocationHelpers.GetLineSpan(SyntaxToken token)
   at StyleCop.Analyzers.LayoutRules.SA1502ElementMustNotBeOnASingleLine.CheckViolation(SyntaxNodeAnalysisContext context, SyntaxToken openBraceToken, SyntaxToken closeBraceToken)
   at StyleCop.Analyzers.LayoutRules.SA1502ElementMustNotBeOnASingleLine.HandleBaseTypeDeclaration(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__62`1.<ExecuteSyntaxNodeAction>b__62_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

Analyzer 'StyleCop.Analyzers.LayoutRules.SA1502ElementMustNotBeOnASingleLine' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
Exception occurred with following context:
Compilation: MyCompany.App.WebApi
SyntaxTree: C:\Users\stark\source\repos\MyCompany.App\src\MyCompany.App.WebApi\Infrastructure\EmailTemplateInfo.cs
SyntaxNode: public record EmailModelInfo(string ... [RecordDeclarationSyntax]@[576..679) (21,4)-(21,107)

System.NullReferenceException: Object reference not set to an instance of an object.
   at StyleCop.Analyzers.Helpers.LocationHelpers.GetLineSpan(SyntaxToken token)
   at StyleCop.Analyzers.LayoutRules.SA1502ElementMustNotBeOnASingleLine.CheckViolation(SyntaxNodeAnalysisContext context, SyntaxToken openBraceToken, SyntaxToken closeBraceToken)
   at StyleCop.Analyzers.LayoutRules.SA1502ElementMustNotBeOnASingleLine.HandleBaseTypeDeclaration(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__62`1.<ExecuteSyntaxNodeAction>b__62_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

Analyzer 'StyleCop.Analyzers.LayoutRules.SA1502ElementMustNotBeOnASingleLine' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
Exception occurred with following context:
Compilation: MyCompany.App.WebApi
SyntaxTree: C:\Users\stark\source\repos\MyCompany.App\src\MyCompany.App.WebApi\Infrastructure\EmailTemplateInfo.cs
SyntaxNode: public record EmailTemplateInfo ... [RecordDeclarationSyntax]@[294..568) (10,4)-(19,41)

System.NullReferenceException: Object reference not set to an instance of an object.
   at StyleCop.Analyzers.Helpers.LocationHelpers.GetLineSpan(SyntaxToken token)
   at StyleCop.Analyzers.LayoutRules.SA1502ElementMustNotBeOnASingleLine.CheckViolation(SyntaxNodeAnalysisContext context, SyntaxToken openBraceToken, SyntaxToken closeBraceToken)
   at StyleCop.Analyzers.LayoutRules.SA1502ElementMustNotBeOnASingleLine.HandleBaseTypeDeclaration(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__62`1.<ExecuteSyntaxNodeAction>b__62_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

Analyzer 'StyleCop.Analyzers.LayoutRules.SA1502ElementMustNotBeOnASingleLine' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
Exception occurred with following context:
Compilation: MyCompany.App.WebApi
SyntaxTree: C:\Users\stark\source\repos\MyCompany.App\src\MyCompany.App.WebApi\Infrastructure\EmailTemplateInfo.cs
SyntaxNode: public record EmailModelInfo(string ... [RecordDeclarationSyntax]@[576..679) (21,4)-(21,107)

System.NullReferenceException: Object reference not set to an instance of an object.
   at StyleCop.Analyzers.Helpers.LocationHelpers.GetLineSpan(SyntaxToken token)
   at StyleCop.Analyzers.LayoutRules.SA1502ElementMustNotBeOnASingleLine.CheckViolation(SyntaxNodeAnalysisContext context, SyntaxToken openBraceToken, SyntaxToken closeBraceToken)
   at StyleCop.Analyzers.LayoutRules.SA1502ElementMustNotBeOnASingleLine.HandleBaseTypeDeclaration(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__62`1.<ExecuteSyntaxNodeAction>b__62_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

```

**Comment by sharwell** [comment] 2020-12-29 15:52
Duplicate of #3272

**Closed by sharwell** 2020-12-29 15:52 UTC
