### ISSUE TITLE
StyleCop Analyzer Export

### ISSUE THREAD

**Issue by agentschmitt** [DotNetAnalyzers/StyleCopAnalyzers#1178] opened 2015-08-10 14:35 UTC
Could you please add a tool, msbuild task or something similar that can generate a xml report for the stylecop violations.

The old stylecop project had an msbuild task to generate a xml file which can be used in continuous integration enviroments like team city or jenkins.

I tried doing this with your StyleCopTester tool but this seems not to consider the ruleset from project and also has just output of total warning count and no more details.

Would really be nice to have a option for generating an xml export for stylecop analyzers in an stylecop  compatible format so we have a full replacement of stylecop.

**Comment by sharwell** [comment] 2015-08-10 14:53
Hi @agentschmitt and welcome to the project. :smile: 

This is more or less a duplicate of #1090, which includes ideas for implementing functionality like this. Currently StyleCopAnalyzers doesn't export an XML file, but it does expose information about violations through a standard API that can be used to export any needed format. Since the "new" way to export information from analyzers is to simply report it during the standard build process, it seems like the task for this project is already complete.

**Comment by sharwell** [comment] 2015-08-13 10:58
@pdelvo @AArnott I'm planning to close this as outside the scope of this project. I don't believe this tool is as necessary for this project as it was for StyleCop classic for the following reasons:

1. Analyzers are directly integrated into MSBuild. You can't build the project and *not* have the warnings reported for enabled rules. StyleCop classic used a separate pass from compilation. The project build output already functions as the report.
2. Most of the diagnostics now have code fixes that support fixing all violations of style rules in one operation. It's much less likely for fixes to these rules to be delayed (and thus need a report) because the rules are almost trivial to follow in the first place.

**Comment by AArnott** [comment] 2015-08-14 03:53
I agree, @sharwell

**Closed** 2015-08-14 04:24 UTC
