### ISSUE TITLE
SA1008 conflicting with C# 7 Tuples

### ISSUE THREAD

**Issue by zuckerthoben** [DotNetAnalyzers/StyleCopAnalyzers#2458] opened 2017-06-22 14:45 UTC
The following line results in SA1008 being thrown on the returning tuple, but it makes no sense here.

`public (Appointment a, FolderId folderId) ConstructSendableExchangeAppointment(ExchangeAppointment ea)`

The fix is:

`public(Appointment a, FolderId folderId) ConstructSendableExchangeAppointment(ExchangeAppointment ea)`

This cant be right

**Comment by sharwell** [comment] 2017-06-22 15:14
Duplicate of #2308. This was fixed in 1.1.0-beta003, which is the first version of the project to support C# 7. I highly recommend upgrading since it sounds like you are using the new features.

**Closed by sharwell** 2017-06-22 15:14 UTC

**Comment by zuckerthoben** [comment] 2017-06-22 15:29
Awkward that the search did not show me this issue, when I searched for SA1008. Thank you anyway 👍

**Comment by sharwell** [comment] 2017-06-22 15:37
No problem at all 👍
