### ISSUE TITLE
Plan for a non-beta Nuget version?

### ISSUE THREAD

**Issue by bbarrette-msft** [DotNetAnalyzers/StyleCopAnalyzers#3571] opened 2022-11-03 18:21 UTC
Hey!

I was wondering if there were any plans to have a new official Nuget release out for this package, since the last one goes back to April 2019.

We have a policy to not use beta versions of packages, and I think everyone would benefit from seeing all the changes done over the years as an official release.

Thanks in advance for your answer!
Bruno

**Comment by bjornhellander** [comment] 2022-11-07 08:03
Hi! See for example #3500  and https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/3420#issuecomment-1058215862, unless you get an answer directly from @sharwell.

**Comment by bbarrette-msft** [comment] 2022-11-07 13:05
Thanks for that @bjornhellander , I hadn't found those answers while searching.

**Comment by ssg** [comment] 2022-11-13 20:18
Perhaps the releases should be versioned by the C# language features they fully support? For example: 8.0.x for the latest stable version that supports 8.0.0 features fully, (and other C# versions partially)? 

Beta gives out the wrong impression that the that version isn't very well tested which isn't the case here.

cc @sharwell

**Comment by cakescience** [comment] 2023-05-09 06:00
@sharwell any plan for the release of a new version? Even if it is still a beta version. The latest version was released in May 2022, which is a bit old.

**Comment by sharwell** [comment] 2024-01-26 17:23
Duplicate of #3500

**Closed by sharwell** 2024-01-26 17:23 UTC
