### ISSUE TITLE
SA1633 should not be shown for generated files

### ISSUE THREAD

**Issue by orellabac** [DotNetAnalyzers/StyleCopAnalyzers#2754] opened 2018-08-17 16:32 UTC
Description
I use some nugets which during the build process, generate some files. The files have the .generated.cs termination which is ignore on the SonarQ Server but locally an warning is reported.

Repro steps
Please provide the steps required to reproduce the problem

Add a file like. Example.generated.cs

Add a header like:

#pragma warning disable
#line 1 "S:\PBNetDCP\src\DCP\Application.cs"

The pragma on the first line should disable any further analysis

Expected behavior
No warning. Should be reported at all.

Actual behavior
Warning SA1633 The file header is missing or not located at the top of the file. Project1.csproj S:\src\Application.Hi5765hs.generated.cs 1 Active

Known workarounds
No known workarounds

Related information
SonarC# Version using nuget SonarAnalyzer.CSharp version 7.3.0.5690
Visual Studio Version 2017
If running through the Scanner for MSBuild, its version

**Comment by sharwell** [comment] 2018-08-17 22:49
Duplicate of #1701

**Closed by sharwell** 2018-08-17 22:49 UTC
