### ISSUE TITLE
SA1000  C# 9.0 Target-typed New Expression Spacing

### ISSUE THREAD

**Issue by tscafeFigo** [DotNetAnalyzers/StyleCopAnalyzers#3399] opened 2021-11-09 19:57 UTC
C# 9.0 has the ability to not require type specification for constructors when the type is known.
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/target-typed-new

Currently SA1000 requires a space after the word new.

This new feature should not require spacing and should be added to the following excerpt.
`The new keyword is part of a generic type constraint. In this case there should be no space between the new keyword and the opening parenthesis.`

https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1000.md#rule-description

Expected `Foo foo = new()`
Actual `Foo foo = new ()`

**Comment by sharwell** [comment] 2021-11-10 16:44
Duplicate of #3214

**Closed by sharwell** 2021-11-10 16:44 UTC
Labels: duplicate
