### ISSUE TITLE
SA1313 should allow discard parameter names

### ISSUE THREAD

**Issue by JohanLarsson** [DotNetAnalyzers/StyleCopAnalyzers#3089] opened 2019-12-08 09:17 UTC
```cs
                                                     ↓ SA1313 warns here
private static void OnChanged(object? sender, object _)
{
    ...
}
```

**Comment by sharwell** [comment] 2019-12-09 20:09
Duplicate of #2599

**Closed by sharwell** 2019-12-09 20:09 UTC
