### ISSUE TITLE
False positive: SA1010 cannot handle the new list-initializer syntax

### ISSUE THREAD

**Issue by hdkesting** [DotNetAnalyzers/StyleCopAnalyzers#3756] opened 2023-12-19 15:07 UTC
With C#12, you can do this:

    int[] a = [1, 2, 3, 4, 5, 6, 7, 8];

(note the square brackets around the list of numbers)
However, Stylecop gives an SA1010 warning (Opening square brackets must not be preceded by a space) on the `[` just before the 1.
The warning would be correct for `int  []`

ref: https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-12#collection-expressions

**Comment by bjornhellander** [comment] 2023-12-19 17:15
Duplicate of #3687. Fixed, but not yet released.

**Comment by sharwell** [comment] 2023-12-19 18:39
Duplicate of #3687

**Closed by sharwell** 2023-12-19 18:39 UTC
