### ISSUE TITLE
Add configurability for SA1413

### ISSUE THREAD

**Issue by jez9999** [DotNetAnalyzers/StyleCopAnalyzers#3153] opened 2020-05-22 09:08 UTC
For rule `SA1413:Use trailing comma in multi-line initializers`...

I'd like there to be configuration added to the `stylecop.json` Readability rules allowing you to specify which of the different types of multi-line initializer the rule should apply to: `objectInitializer`, `enum`, `array`, etc.

Personally I only want the rule to apply to enums and arrays for my code.

**Comment by sharwell** [comment] 2020-05-28 04:15
This is a maintainability rule, not a readability rule. See also #2884.

If you are looking for a readability rule (or ability to configure some other behavior based on readability), my recommendation would be to disable this rule altogether.

**Comment by sharwell** [comment] 2020-05-28 04:16
Duplicate of #2416

**Closed by sharwell** 2020-05-28 04:16 UTC

**Comment by jez9999** [comment] 2020-05-28 07:59
> This is a maintainability rule, not a readability rule. See also [#2884 (comment)](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/2884#issuecomment-463471991).

Looks like this is wrong then:
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/b6b9b0249a142132453873a677b7f09d7d65f34b/StyleCop.Analyzers/StyleCop.Analyzers/MaintainabilityRules/SA1413UseTrailingCommasInMultiLineInitializers.cs#L58

> If you are looking for a readability rule (or ability to configure some other behavior based on readability), my recommendation would be to disable this rule altogether.

Why should this be any less configurable just because it's a maintainability rule?

**Comment by sharwell** [comment] 2020-05-28 08:02
> Looks like this is wrong then:

Yes, you are correct here.

> Why should this be any less configurable just because it's a maintainability rule?

Configuring the rule would completely defeat its purpose:
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1413.md#rationale

**Comment by jez9999** [comment] 2020-05-28 08:07
> 
> 
> > Looks like this is wrong then:
> 
> Yes, you are correct here.
> 
> > Why should this be any less configurable just because it's a maintainability rule?
> 
> Configuring the rule would completely defeat its purpose:
> https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1413.md#rationale

Actually, it would only defeat its purpose for types it had configured not to apply to, which is precisely what I want to do.  Turning it off altogether, which you recommended, completely defeats its purpose.

**Comment by sharwell** [comment] 2020-05-28 08:12
I would suggest upvoting https://github.com/dotnet/roslyn/issues/27712. This feature proposal is designed to cover exactly this kind of request without placing additional implementation burden on analyzer projects. 👍
