### ISSUE TITLE
SA1649 and SA1402 not reported

### ISSUE THREAD

**Issue by mark-monteiro** [DotNetAnalyzers/StyleCopAnalyzers#3443] opened 2022-01-26 17:32 UTC
For a few months now I have noticed that SA1402FileMayOnlyContainASingleType and SA1649FileNameMustMatchTypeName are not being reported in my projects.

At first I assumed this was an issue with my setup, but I created a minimum reproducible example and the issue still persists: https://gitlab.com/senti.mark.monteiro/stylecop-issue-repro

Let me know if there is any additional information I can provide

**Comment by sharwell** [comment] 2022-01-26 18:15
Duplicate of #3435

**Closed by sharwell** 2022-01-26 18:15 UTC
