### ISSUE TITLE
SA1008 false positive on cast in lambda in right-hand side of null coalescing op

### ISSUE THREAD

**Issue by generateui** [DotNetAnalyzers/StyleCopAnalyzers#3449] opened 2022-01-31 14:53 UTC
I pass in a lambda expression `(mb, ex)` calling a method `Write` having arguments `LogLevel.Info` and null coalescing operator.

On null coalescing operator argument, a function is passed in `mb` and a parenthesed lambda. This parenthesed lambda returns a parenthesed value (string concatanation).  

```csharp
(mb, ex) => Write((int)LogLevel.Info, mb ?? (_ =>_ ("Exception during " + myName))
```

Most likely this example can be simplified, as I suspect the culprit is in the parenthesed string concat as return from a shorthand lambda.

**Comment by bjornhellander** [comment] 2022-05-04 19:21
Where do you get SA1008?
Why do you think this is a false positive?

Assuming that _ is a `Action<string>` or a `Func<string, string>`, this looks correct to me, because `_ ("Exception during " + myName)` is  a method invocation and there should be no space before its opening parenthesis.

**Comment by bjornhellander** [comment] 2022-06-19 11:25
@generateui, if you still thinks this is a bug, please answer the questions above and provide a compilable example so it is possible to understand your code.

**Comment by sharwell** [comment] 2022-06-22 14:41
Closing this one as by design (detail in https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/3449#issuecomment-1117729579)

**Closed by sharwell** 2022-06-22 14:41 UTC
