### ISSUE TITLE
SA1119 patches may cause code to be unenforceable

### ISSUE THREAD

**Issue by yb199478** [DotNetAnalyzers/StyleCopAnalyzers#2940] opened 2019-04-19 04:08 UTC
The following code causes SA1119：
```csharp
public void Foo(string str, int num)
{
    if (!(str is null) && num > 10)
    {
    }
}
```

After repairing according to the patch：

```csharp
public void Foo(string str, int num)
{
    if (!str is null && num > 10)
    {
    }
}
```

Code: `!str is null` it is invalid

**Comment by sharwell** [comment] 2019-04-19 04:27
Duplicate of #2372

**Closed by sharwell** 2019-04-19 04:27 UTC

**Comment by yb199478** [comment] 2019-04-19 05:11
thanks
