### ISSUE TITLE
SA1122 incorrectly triggered in pattern matching

### ISSUE THREAD

**Issue by matteo-mosca** [DotNetAnalyzers/StyleCopAnalyzers#3407] opened 2021-11-26 12:14 UTC
When using pattern matching only constant values can be used, so string.Empty is not a valid value.

When inputting empty double quotes "" to satisfy the requirement the SA1122 is incorrectly triggered.

**Comment by sharwell** [comment] 2021-11-29 22:56
Duplicate of #3028

**Closed by sharwell** 2021-11-29 22:56 UTC
