### ISSUE TITLE
Is possible to configure `this` keyword?

### ISSUE THREAD

**Issue by kkorus** [DotNetAnalyzers/StyleCopAnalyzers#2789] opened 2018-09-20 11:06 UTC
Is it possible to configure `this` keyword. 
I want to enable rule `SA1101 Prefix local calls with this` but only for fields of a class, not a method.

Ideal: 
```csharp
var a = privateField; // warning, missing this
var b = PrivateOrPublicMethod(); // no warning
```

**Comment by sharwell** [comment] 2018-09-20 11:47
No, it is not currently possible.

**Comment by kkorus** [comment] 2018-09-20 12:46
@sharwell Would be nice to have it 😉

**Comment by sharwell** [comment] 2018-09-20 12:58
Duplicate of #2612

**Closed by sharwell** 2018-09-20 12:58 UTC
