### ISSUE TITLE
SA1008 incorrect warning

### ISSUE THREAD

**Issue by truegoodwill** [DotNetAnalyzers/StyleCopAnalyzers#3338] opened 2021-04-24 00:45 UTC
This warning should not happen:

![image](https://user-images.githubusercontent.com/77037161/115941754-cb5d8f00-a474-11eb-9b67-9ce3365f67d9.png)

**Comment by sharwell** [comment] 2021-04-24 01:46
Duplicate of #3230

**Closed by sharwell** 2021-04-24 01:46 UTC

**Comment by truegoodwill** [comment] 2021-04-24 02:15
thank you
