### ISSUE TITLE
Is there a SA rule to help enforce rule 6 of the CoreFx coding guidelines?

### ISSUE THREAD

**Issue by rkeithhill** [DotNetAnalyzers/StyleCopAnalyzers#1929] opened 2015-12-07 16:58 UTC
Specifically that there should be a blank line between top level groups and System namespaces come first followed by alphabetically sorted namespaces after that e.g.:
```
using System;

using Acme;
```
https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md

**Comment by sharwell** [comment] 2015-12-07 17:32
Duplicate of #1787.

:memo: The linked issue is a proposal which has not yet been accepted. If you want to see this feature added, please consider voting for it.

**Closed by sharwell** 2015-12-07 17:33 UTC
