### ISSUE TITLE
Throwaway variable triggers SA1312 (Variable names should begin with lower-case letter)

### ISSUE THREAD

**Issue by mikernet** [DotNetAnalyzers/StyleCopAnalyzers#3170] opened 2020-07-07 06:19 UTC
If the underscore throwaway variable name `_` is used I don't think it should trigger this rule, i.e:

```C#
        private void EnsureExists()
        {
            var _ = Attributes;
        }
```

**Comment by sharwell** [comment] 2020-07-07 06:23
The discard syntax does not require the `var` keyword:

```csharp
_ = Attributes;
```

**Comment by sharwell** [comment] 2020-07-07 06:23
Duplicate of #3057

**Closed by sharwell** 2020-07-07 06:23 UTC

**Comment by mikernet** [comment] 2020-07-07 07:50
***facepalm*** Thanks :)
