### ISSUE TITLE
Bug in code fix for SA1139 Use literal suffix notation instead of casting

### ISSUE THREAD

**Issue by GregReddick** [DotNetAnalyzers/StyleCopAnalyzers#2362] opened 2017-05-27 22:43 UTC
I have a line of code that looks like this (part of an enum):
```csharp
HasSubFolder = unchecked((int)0x80000000),
```
It generates SA1139 Use literal suffix notation instead of casting. When I apply the code fix, it changes the hex value to decimal. I wind up with:
```csharp
HasSubFolder = unchecked(-2147483648),
```
The code fix should not change hex values to decimal.

**Comment by tmaczynski** [comment] 2017-07-15 09:49
I will fix this.

**Comment by sharwell** [comment] 2018-06-10 19:13
Duplicate of #2275

**Closed by sharwell** 2018-06-10 19:13 UTC
Labels: bug
