### ISSUE TITLE
SA1135CodeFixProvider InvalidCastException

### ISSUE THREAD

**Issue by AArnott** [DotNetAnalyzers/StyleCopAnalyzers#2955] opened 2019-05-07 14:00 UTC
A code fix provider was disabled. This was the callstack Roslyn reported:

```
System.InvalidCastException : Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.IdentifierNameSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.QualifiedNameSyntax'.
   at StyleCop.Analyzers.ReadabilityRules.SA1135CodeFixProvider.GetReplacementName(TypeSyntax symbolNameSyntax,TypeSyntax nameSyntax)
   at StyleCop.Analyzers.ReadabilityRules.SA1135CodeFixProvider.GetReplacementNode(SemanticModel semanticModel,UsingDirectiveSyntax node,CancellationToken cancellationToken)
   at async StyleCop.Analyzers.ReadabilityRules.SA1135CodeFixProvider.GetTransformedDocumentAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
```

**Comment by bjornhellander** [comment] 2022-07-17 12:39
It's been a while, so no chance of you remembering what the code actually looked like before applying the fix? :-)
Or what analyzer version was used?

**Comment by AArnott** [comment] 2022-07-17 13:12
I'm afraid not.

**Comment by bjornhellander** [comment] 2023-06-25 09:24
I had a look at this again just now. Given the current code, this crash makes little sense to me. I also notice that this analyzer was updated regarding qualified names (which the crash is related to) in about the same time as this was reported. Since we also have no repro code or info about used version, I suggest closing this as not reproducable. What do you think, @sharwell?

**Closed** 2023-06-26 13:39 UTC
Labels: bug
