### ISSUE TITLE
SA1119 Incorrectly suggests removing brackets

### ISSUE THREAD

**Issue by hisuwh** [DotNetAnalyzers/StyleCopAnalyzers#2597] opened 2018-01-17 16:44 UTC
Stylecop analyzer rule is telling me to remove the extra parentheses in this line: 

`if (!(obj is TestValue testValue))``

But the result does not compile as you can not use the `!` operator with type `object`:
`if (!obj is TestValue testValue)`

**Comment by sharwell** [comment] 2018-01-17 17:01
Duplicate of #2372

**Closed by sharwell** 2018-01-17 17:01 UTC
