### ISSUE TITLE
SA1119 false positive for parenthesis around `x switch {}` expression

### ISSUE THREAD

**Issue by n0099** [DotNetAnalyzers/StyleCopAnalyzers#3730] opened 2023-11-21 13:43 UTC
https://github.com/n0099/open-tbm/blob/af3fe85e196e0ffaa0fa881e86b2c23999e0f736/c%23/imagePipeline/src/Ocr/PaddleOcrRecognizerAndDetector.cs#L25-L34
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/switch-expression

**Comment by bjornhellander** [comment] 2023-11-25 12:51
Created a pull request since similar cases are already allowed by SA1119.

**Comment by sharwell** [comment] 2023-11-28 15:43
@bjornhellander Is this not a duplicate of #3200 and/or #3460?

**Comment by bjornhellander** [comment] 2023-11-28 17:26
No. What caused it to trigger this time was the **invocation** on the last line of the provided repro code.
It can be simplified to this: `await (x switch ...)(y)` but it also triggers on this: `(x switch ...)(y)`

**Closed** 2023-11-28 18:48 UTC
