### ISSUE TITLE
SA1009 ans SA1024 clashses in the middle of a line

### ISSUE THREAD

**Issue by modestotech** [DotNetAnalyzers/StyleCopAnalyzers#3834] opened 2024-05-07 07:39 UTC
This behavior seems a bit messy. A space and colon in the middle of a line should be accepted by SA1009, right?

![capture02](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/assets/31730051/2f50dbf3-2d37-42b4-acae-9d69c9253da5)

**Comment by bjornhellander** [comment] 2024-05-07 16:03
Duplicate of #3248

**Comment by modestotech** [comment] 2024-05-07 19:24
Yes, sorry about not mentioning the version. You're right, bumped to the beta version and now it works. Please close.

**Comment by sharwell** [comment] 2024-05-09 22:06
Duplicate of #3248

**Closed by sharwell** 2024-05-09 22:06 UTC
