### ISSUE TITLE
SA1313 Allow `__` as name for lambda parameter.

### ISSUE THREAD

**Issue by JohanLarsson** [DotNetAnalyzers/StyleCopAnalyzers#2645] opened 2018-03-18 13:28 UTC
```cs
namespace RoslynSandbox
{
    using System;

    public class Foo
    {
        public Foo()
        {
            Console.CancelKeyPress += (_, __) => Console.WriteLine("Cancel");
        }
    }
}
```

Should not be a warning for ^ IMO.

**Comment by sharwell** [comment] 2018-03-18 13:34
Duplicate of #1606

**Comment by JohanLarsson** [comment] 2018-03-18 13:35
Gah, I did a search, sry.

**Closed by sharwell** 2018-03-18 13:34 UTC

**Comment by sharwell** [comment] 2018-03-18 14:09
No problem 😄
