### ISSUE TITLE
SA1118 Anonymous method exception in documentation does not match behavior

### ISSUE THREAD

**Issue by appel1** [DotNetAnalyzers/StyleCopAnalyzers#1596] opened 2015-10-05 11:16 UTC
The documentation states that anonymous methods are excepted from this rule. The following code violate this rule using StyleCopAnalyzers but not StyleCop. 

```csharp
                this.dispatcher.Invoke(
                    DispatcherPriority.Send,
                    new Action(
                        () =>
                        {
                            try
                            {
                                DoStuff();
                                tcs.SetResult(null);
                            }
                            catch (Exception e)
                            {
                                tcs.SetException(e);
                            }
                        }));
```

**Comment by sharwell** [comment] 2015-10-05 11:43
It looks like you found a case where StyleCop "classic" wasn't following its own rules. Technically the second argument here is an object initializer expression which happens to have an anonymous method as its first argument.

I created issue #1597 with a proposed solution to this discrepancy.

**Comment by sharwell** [comment] 2015-10-26 05:01
Now that proposal #1597 is accepted and awaiting implementation, I'm going to mark this issue as a duplicate of it so it doesn't get lost. :smile:

**Closed by sharwell** 2015-10-26 05:01 UTC
