### ISSUE TITLE
Various new warnings showed up after updating to beta10

### ISSUE THREAD

**Issue by NikolayIT** [DotNetAnalyzers/StyleCopAnalyzers#1444] opened 2015-09-10 07:42 UTC
![stylecopwarnings](https://cloud.githubusercontent.com/assets/3106986/9782813/9f20dace-57a8-11e5-9695-7da9e3f2851d.png)

    Severity	Code	Description	Project	File	Line
    Warning	CS8032	An instance of analyzer StyleCop.Analyzers.OrderingRules.SA1216UsingStaticDirectivesMustBePlacedAtTheCorrectLocation cannot be created from C:\Dev\2015\SantaseGameEngine\Source\packages\StyleCop.Analyzers.1.0.0-beta010\analyzers\dotnet\cs\StyleCop.Analyzers.dll: Could not load type 'StyleCop.Analyzers.OrderingRules.SA1216UsingStaticDirectivesMustBePlacedAtTheCorrectLocation' from assembly 'StyleCop.Analyzers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=97d9e3aa481481c8'..	Santase.AI.DummyPlayer		1
    Warning	MissingAnalyzerReference	Analyzer assembly 'C:\Dev\2015\SantaseGameEngine\Source\packages\StyleCop.Analyzers.1.0.0-beta010\analyzers\dotnet\cs\Newtonsoft.Json.dll' depends on 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' but it was not found. Analyzers may not run correctly.	Santase.Logic		1
    Warning	MissingAnalyzerReference	Analyzer assembly 'C:\Dev\2015\SantaseGameEngine\Source\packages\StyleCop.Analyzers.1.0.0-beta010\analyzers\dotnet\cs\Newtonsoft.Json.dll' depends on 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' but it was not found. Analyzers may not run correctly.	Santase.AI.DummyPlayer		1
    Warning	MissingAnalyzerReference	Analyzer assembly 'C:\Dev\2015\SantaseGameEngine\Source\packages\StyleCop.Analyzers.1.0.0-beta010\analyzers\dotnet\cs\Newtonsoft.Json.dll' depends on 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' but it was not found. Analyzers may not run correctly.	Santase.AI.SmartPlayer		1
    Warning	MissingAnalyzerReference	Analyzer assembly 'C:\Dev\2015\SantaseGameEngine\Source\packages\StyleCop.Analyzers.1.0.0-beta010\analyzers\dotnet\cs\Newtonsoft.Json.dll' depends on 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' but it was not found. Analyzers may not run correctly.	Santase.ConsoleUI		1
    Warning	MissingAnalyzerReference	Analyzer assembly 'C:\Dev\2015\SantaseGameEngine\Source\packages\StyleCop.Analyzers.1.0.0-beta010\analyzers\dotnet\cs\Newtonsoft.Json.dll' depends on 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' but it was not found. Analyzers may not run correctly.	Santase.Logic.Tests		1
    Warning	CS8032	An instance of analyzer StyleCop.Analyzers.ReadabilityRules.SA1128ConstructorInitializerMustBeOnOwnLine cannot be created from C:\Dev\2015\SantaseGameEngine\Source\packages\StyleCop.Analyzers.1.0.0-beta010\analyzers\dotnet\cs\StyleCop.Analyzers.dll: Could not load type 'StyleCop.Analyzers.ReadabilityRules.SA1128ConstructorInitializerMustBeOnOwnLine' from assembly 'StyleCop.Analyzers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=97d9e3aa481481c8'..	Santase.Logic		1
    Warning	CS8032	An instance of analyzer StyleCop.Analyzers.ReadabilityRules.SA1128ConstructorInitializerMustBeOnOwnLine cannot be created from C:\Dev\2015\SantaseGameEngine\Source\packages\StyleCop.Analyzers.1.0.0-beta010\analyzers\dotnet\cs\StyleCop.Analyzers.dll: Could not load type 'StyleCop.Analyzers.ReadabilityRules.SA1128ConstructorInitializerMustBeOnOwnLine' from assembly 'StyleCop.Analyzers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=97d9e3aa481481c8'..	Santase.AI.DummyPlayer		1
    Warning	CS8032	An instance of analyzer StyleCop.Analyzers.ReadabilityRules.SA1128ConstructorInitializerMustBeOnOwnLine cannot be created from C:\Dev\2015\SantaseGameEngine\Source\packages\StyleCop.Analyzers.1.0.0-beta010\analyzers\dotnet\cs\StyleCop.Analyzers.dll: Could not load type 'StyleCop.Analyzers.ReadabilityRules.SA1128ConstructorInitializerMustBeOnOwnLine' from assembly 'StyleCop.Analyzers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=97d9e3aa481481c8'..	Santase.AI.SmartPlayer		1
    Warning	CS8032	An instance of analyzer StyleCop.Analyzers.ReadabilityRules.SA1128ConstructorInitializerMustBeOnOwnLine cannot be created from C:\Dev\2015\SantaseGameEngine\Source\packages\StyleCop.Analyzers.1.0.0-beta010\analyzers\dotnet\cs\StyleCop.Analyzers.dll: Could not load type 'StyleCop.Analyzers.ReadabilityRules.SA1128ConstructorInitializerMustBeOnOwnLine' from assembly 'StyleCop.Analyzers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=97d9e3aa481481c8'..	Santase.ConsoleUI		1
    Warning	CS8032	An instance of analyzer StyleCop.Analyzers.ReadabilityRules.SA1128ConstructorInitializerMustBeOnOwnLine cannot be created from C:\Dev\2015\SantaseGameEngine\Source\packages\StyleCop.Analyzers.1.0.0-beta010\analyzers\dotnet\cs\StyleCop.Analyzers.dll: Could not load type 'StyleCop.Analyzers.ReadabilityRules.SA1128ConstructorInitializerMustBeOnOwnLine' from assembly 'StyleCop.Analyzers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=97d9e3aa481481c8'..	Santase.Logic.Tests		1
    Warning	CS8032	An instance of analyzer StyleCop.Analyzers.ReadabilityRules.SA1127GenericTypeConstraintsMustBeOnOwnLine cannot be created from C:\Dev\2015\SantaseGameEngine\Source\packages\StyleCop.Analyzers.1.0.0-beta010\analyzers\dotnet\cs\StyleCop.Analyzers.dll: Could not load type 'StyleCop.Analyzers.ReadabilityRules.SA1127GenericTypeConstraintsMustBeOnOwnLine' from assembly 'StyleCop.Analyzers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=97d9e3aa481481c8'..	Santase.Logic		1
    Warning	CS8032	An instance of analyzer StyleCop.Analyzers.ReadabilityRules.SA1127GenericTypeConstraintsMustBeOnOwnLine cannot be created from C:\Dev\2015\SantaseGameEngine\Source\packages\StyleCop.Analyzers.1.0.0-beta010\analyzers\dotnet\cs\StyleCop.Analyzers.dll: Could not load type 'StyleCop.Analyzers.ReadabilityRules.SA1127GenericTypeConstraintsMustBeOnOwnLine' from assembly 'StyleCop.Analyzers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=97d9e3aa481481c8'..	Santase.AI.DummyPlayer		1
    Warning	CS8032	An instance of analyzer StyleCop.Analyzers.ReadabilityRules.SA1127GenericTypeConstraintsMustBeOnOwnLine cannot be created from C:\Dev\2015\SantaseGameEngine\Source\packages\StyleCop.Analyzers.1.0.0-beta010\analyzers\dotnet\cs\StyleCop.Analyzers.dll: Could not load type 'StyleCop.Analyzers.ReadabilityRules.SA1127GenericTypeConstraintsMustBeOnOwnLine' from assembly 'StyleCop.Analyzers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=97d9e3aa481481c8'..	Santase.AI.SmartPlayer		1
    Warning	CS8032	An instance of analyzer StyleCop.Analyzers.ReadabilityRules.SA1127GenericTypeConstraintsMustBeOnOwnLine cannot be created from C:\Dev\2015\SantaseGameEngine\Source\packages\StyleCop.Analyzers.1.0.0-beta010\analyzers\dotnet\cs\StyleCop.Analyzers.dll: Could not load type 'StyleCop.Analyzers.ReadabilityRules.SA1127GenericTypeConstraintsMustBeOnOwnLine' from assembly 'StyleCop.Analyzers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=97d9e3aa481481c8'..	Santase.ConsoleUI		1
    Warning	CS8032	An instance of analyzer StyleCop.Analyzers.ReadabilityRules.SA1127GenericTypeConstraintsMustBeOnOwnLine cannot be created from C:\Dev\2015\SantaseGameEngine\Source\packages\StyleCop.Analyzers.1.0.0-beta010\analyzers\dotnet\cs\StyleCop.Analyzers.dll: Could not load type 'StyleCop.Analyzers.ReadabilityRules.SA1127GenericTypeConstraintsMustBeOnOwnLine' from assembly 'StyleCop.Analyzers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=97d9e3aa481481c8'..	Santase.Logic.Tests		1
    Warning	CS8032	An instance of analyzer StyleCop.Analyzers.OrderingRules.SA1216UsingStaticDirectivesMustBePlacedAtTheCorrectLocation cannot be created from C:\Dev\2015\SantaseGameEngine\Source\packages\StyleCop.Analyzers.1.0.0-beta010\analyzers\dotnet\cs\StyleCop.Analyzers.dll: Could not load type 'StyleCop.Analyzers.OrderingRules.SA1216UsingStaticDirectivesMustBePlacedAtTheCorrectLocation' from assembly 'StyleCop.Analyzers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=97d9e3aa481481c8'..	Santase.Logic		1
    Warning	CS8032	An instance of analyzer StyleCop.Analyzers.OrderingRules.SA1216UsingStaticDirectivesMustBePlacedAtTheCorrectLocation cannot be created from C:\Dev\2015\SantaseGameEngine\Source\packages\StyleCop.Analyzers.1.0.0-beta010\analyzers\dotnet\cs\StyleCop.Analyzers.dll: Could not load type 'StyleCop.Analyzers.OrderingRules.SA1216UsingStaticDirectivesMustBePlacedAtTheCorrectLocation' from assembly 'StyleCop.Analyzers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=97d9e3aa481481c8'..	Santase.AI.SmartPlayer		1
    Warning	CS8032	An instance of analyzer StyleCop.Analyzers.OrderingRules.SA1216UsingStaticDirectivesMustBePlacedAtTheCorrectLocation cannot be created from C:\Dev\2015\SantaseGameEngine\Source\packages\StyleCop.Analyzers.1.0.0-beta010\analyzers\dotnet\cs\StyleCop.Analyzers.dll: Could not load type 'StyleCop.Analyzers.OrderingRules.SA1216UsingStaticDirectivesMustBePlacedAtTheCorrectLocation' from assembly 'StyleCop.Analyzers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=97d9e3aa481481c8'..	Santase.ConsoleUI		1
    Warning	CS8032	An instance of analyzer StyleCop.Analyzers.OrderingRules.SA1216UsingStaticDirectivesMustBePlacedAtTheCorrectLocation cannot be created from C:\Dev\2015\SantaseGameEngine\Source\packages\StyleCop.Analyzers.1.0.0-beta010\analyzers\dotnet\cs\StyleCop.Analyzers.dll: Could not load type 'StyleCop.Analyzers.OrderingRules.SA1216UsingStaticDirectivesMustBePlacedAtTheCorrectLocation' from assembly 'StyleCop.Analyzers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=97d9e3aa481481c8'..	Santase.Logic.Tests		1

**Comment by NikolayIT** [comment] 2015-09-10 07:47
I am using VS 2015. Restarting it fixed all warnings except:

    Severity	Code	Description	Project	File	Line
    Warning	MissingAnalyzerReference	Analyzer assembly 'C:\Dev\2015\SantaseGameEngine\Source\packages\StyleCop.Analyzers.1.0.0-beta010\analyzers\dotnet\cs\Newtonsoft.Json.dll' depends on 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' but it was not found. Analyzers may not run correctly.	Santase.Logic		1
    Warning	MissingAnalyzerReference	Analyzer assembly 'C:\Dev\2015\SantaseGameEngine\Source\packages\StyleCop.Analyzers.1.0.0-beta010\analyzers\dotnet\cs\Newtonsoft.Json.dll' depends on 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' but it was not found. Analyzers may not run correctly.	Santase.AI.DummyPlayer		1
    Warning	MissingAnalyzerReference	Analyzer assembly 'C:\Dev\2015\SantaseGameEngine\Source\packages\StyleCop.Analyzers.1.0.0-beta010\analyzers\dotnet\cs\Newtonsoft.Json.dll' depends on 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' but it was not found. Analyzers may not run correctly.	Santase.AI.SmartPlayer		1
    Warning	MissingAnalyzerReference	Analyzer assembly 'C:\Dev\2015\SantaseGameEngine\Source\packages\StyleCop.Analyzers.1.0.0-beta010\analyzers\dotnet\cs\Newtonsoft.Json.dll' depends on 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' but it was not found. Analyzers may not run correctly.	Santase.ConsoleUI		1
    Warning	MissingAnalyzerReference	Analyzer assembly 'C:\Dev\2015\SantaseGameEngine\Source\packages\StyleCop.Analyzers.1.0.0-beta010\analyzers\dotnet\cs\Newtonsoft.Json.dll' depends on 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' but it was not found. Analyzers may not run correctly.	Santase.Logic.Tests		1

**Comment by mwadams** [comment] 2015-09-10 10:37
I have the same problem, also in VS2015.

My projects are all targeting .NET 4.5.1

**Comment by sharwell** [comment] 2015-09-10 11:12
The warnings which disappeared when you restarted Visual Studio are a duplicate of #1391.

The warnings which won't disappear are a duplicate of #1345.

**Closed by sharwell** 2015-09-10 11:12 UTC
