### ISSUE TITLE
SA1312 reports false positive on event

### ISSUE THREAD

**Issue by RalfKoban** [DotNetAnalyzers/StyleCopAnalyzers#1369] opened 2015-09-02 11:27 UTC
Hi,

I just updated to version 1.0.0.-beta9. Now I get false SA1312 violations for classes implementing interfaces that define events, such as in following code snippet:

    public class Demo : INotifyPropertyChanging
    {
        public event PropertyChangingEventHandler PropertyChanging;
    }

Best regards,
Ralf

**Comment by sharwell** [comment] 2015-09-02 12:11
Sorry about this one. :frowning: 

Duplicate of #1340. I'll have a new release out soon that fixes it. I recommend you set SA1312 to disabled until Beta 10.

**Closed** 2015-09-02 12:11 UTC
Labels: duplicate
