### ISSUE TITLE
SA1313ParameterNamesMustBeginWithLowerCaseLetter  - unused params

### ISSUE THREAD

**Issue by kindermannhubert** [DotNetAnalyzers/StyleCopAnalyzers#2173] opened 2016-07-18 11:54 UTC
Maybe SA1313 could ignore parameter names made only from underscores (which marks unused parameter)?

For example:
```C#
button.Click += (_, __) => Console.WriteLine("Click");
```

**Comment by sharwell** [comment] 2016-07-18 13:11
This is a duplicate of #1606 and/or #1343. :smile:

**Closed by sharwell** 2016-07-18 13:11 UTC
Labels: duplicate
